// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.0.0
//     wasmcloud:keyvalue@0.1.0
//     wasmcloud:messaging@0.2.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_messaging_0_2_0_consumer

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"go.wasmcloud.dev/component/imports/wasmcloud_messaging_0_2_0_types"
	"runtime"
	"unsafe"
)

type BrokerMessage = wasmcloud_messaging_0_2_0_types.BrokerMessage

//go:wasmimport wasmcloud:messaging/consumer@0.2.0 request
func wasm_import_request(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 int32, arg5 uintptr)

func Request(subject string, body []uint8, timeoutMs uint32) witTypes.Result[wasmcloud_messaging_0_2_0_types.BrokerMessage, string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(subject))
	pinner.Pin(utf8)
	data := unsafe.Pointer(unsafe.SliceData(body))
	pinner.Pin(data)
	wasm_import_request(uintptr(utf8), uint32(len(subject)), uintptr(data), uint32(len(body)), int32(timeoutMs), returnArea)
	var result witTypes.Result[wasmcloud_messaging_0_2_0_types.BrokerMessage, string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		value0 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4))))
		var option witTypes.Option[string]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4)))) {
		case 0:

			option = witTypes.None[string]()
		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))

			option = witTypes.Some[string](value1)
		default:
			panic("unreachable")
		}

		result = witTypes.Ok[wasmcloud_messaging_0_2_0_types.BrokerMessage, string](wasmcloud_messaging_0_2_0_types.BrokerMessage{value, value0, option})
	case 1:
		value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Err[wasmcloud_messaging_0_2_0_types.BrokerMessage, string](value2)
	default:
		panic("unreachable")
	}
	result3 := result
	return result3

}

//go:wasmimport wasmcloud:messaging/consumer@0.2.0 publish
func wasm_import_publish(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 int32, arg5 uintptr, arg6 uint32, arg7 uintptr)

func Publish(msg wasmcloud_messaging_0_2_0_types.BrokerMessage) witTypes.Result[witTypes.Unit, string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData((msg).Subject))
	pinner.Pin(utf8)
	data := unsafe.Pointer(unsafe.SliceData((msg).Body))
	pinner.Pin(data)
	var option int32
	var option1 uintptr
	var option2 uint32
	switch (msg).ReplyTo.Tag() {
	case witTypes.OptionNone:

		option = int32(0)
		option1 = 0
		option2 = 0
	case witTypes.OptionSome:
		payload := (msg).ReplyTo.Some()
		utf80 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf80)

		option = int32(1)
		option1 = uintptr(utf80)
		option2 = uint32(len(payload))
	default:
		panic("unreachable")
	}
	wasm_import_publish(uintptr(utf8), uint32(len((msg).Subject)), uintptr(data), uint32(len((msg).Body)), option, option1, option2, returnArea)
	var result witTypes.Result[witTypes.Unit, string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, string](witTypes.Unit{})
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Err[witTypes.Unit, string](value)
	default:
		panic("unreachable")
	}
	result3 := result
	return result3

}
