// Generated by `wit-bindgen` 0.61.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.1.0
//     wasmcloud:keyvalue@0.2.0
//     wasmcloud:messaging@0.3.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_nats_0_1_0_jetstream

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"go.wasmcloud.dev/component/imports/wasmcloud_nats_0_1_0_types"
	"runtime"
	"unsafe"
)

type NatsMessage = wasmcloud_nats_0_1_0_types.NatsMessage
type NatsError = wasmcloud_nats_0_1_0_types.NatsError
type HeaderEntry = wasmcloud_nats_0_1_0_types.HeaderEntry

// Ack returned from a JetStream publish.
type PublishAck struct {
	StreamName string
	Sequence   uint64
	// True when the server recognised this message as a duplicate within the
	// stream's duplicate window and did not store it again.
	Duplicate bool
}

// A message retrieved from a JetStream stream (read-only snapshot).
type StoredMessage struct {
	Subject  string
	Sequence uint64
	Data     []uint8
	Headers  witTypes.Option[[]wasmcloud_nats_0_1_0_types.HeaderEntry]
}

// One subject a stream currently holds messages on, with its message count.
type SubjectCount struct {
	Subject string
	Count   uint64
}

// Read-only snapshot of a stream.
type StreamInfo struct {
	Name string
	// Subjects the stream is configured to capture.
	Subjects      []string
	Messages      uint64
	Bytes         uint64
	FirstSequence uint64
	LastSequence  uint64
	ConsumerCount uint64
}

// Read-only snapshot of a consumer, including the limits it was
// provisioned with.
type ConsumerInfo struct {
	Name       string
	StreamName string
	// Singular filter; empty when unset. Consumers may instead use
	// `filter-subjects`; the consumer captures the stream's whole subject
	// space only when both are empty.
	FilterSubject string
	// Multi-subject filter, as provisioned on servers 2.10 and newer. Empty
	// when the consumer uses the singular `filter-subject`, or no filter at
	// all.
	FilterSubjects []string
	// Zero when unset on the consumer.
	MaxAckPending uint64
	// Zero when unset. Pull consumers only.
	MaxWaiting uint64
	// Largest `batch` a single pull may ask for. Zero when unset. A `fetch`
	// above it is refused with `limit-exceeded`, not truncated.
	MaxRequestBatch uint64
	// Largest byte bound a single pull may ask for. Zero when unset. Counts
	// subject, reply subject, and payload — roughly 63 bytes of overhead per
	// small message — so leave margin when sizing against it.
	MaxRequestMaxBytes uint64
	// Zero when unset.
	MaxDeliver uint64
	AckWaitMs  uint64
	// Messages delivered but not yet acknowledged.
	NumAckPending uint64
	// Messages waiting to be delivered.
	NumPending uint64
	// Messages awaiting redelivery after a nak or ack-wait expiry.
	NumRedelivered uint64
}

const (
	// The batch was filled: `batch` messages came back.
	FetchStopBatchFilled uint8 = 0
	// The consumer had no more to give before the timeout elapsed. What came
	// back is everything that was there.
	FetchStopDrained uint8 = 1
	// A byte bound ended the batch early — `max-bytes` on the call, or the
	// consumer's `max-request-max-bytes`. More messages are waiting, and the
	// next fetch picks up where this one stopped.
	FetchStopByteLimit uint8 = 2
)

// Why a fetch stopped delivering.
type FetchStop = uint8

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [resource-drop]message-handle
func resourceDropMessageHandle(handle int32)

// Handle to a single JetStream-delivered message.
//
// Settling is one-shot, but only on success: an `ack`, `nak`, or `term`
// the server accepted retires the handle, and a later settle returns
// `already-settled`. A settle that *failed* on the wire leaves the handle
// usable, so retrying it is correct rather than a lost message.
//
// `in-progress` may be called repeatedly to extend ack-wait. It works
// under `ack-mode: auto` too, where the host owns the settle and every
// other method here returns `ack-owned-by-host`.
type MessageHandle struct {
	handle *witRuntime.Handle
}

func (self *MessageHandle) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *MessageHandle) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *MessageHandle) Handle() int32 {
	return self.handle.Use()
}

func (self *MessageHandle) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropMessageHandle(handle)
	}
}

func MessageHandleFromOwnHandle(handleValue int32) *MessageHandle {
	handle := witRuntime.MakeHandle(handleValue)
	value := &MessageHandle{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropMessageHandle(handleValue)
		}
	}, 0)
	return value
}

func MessageHandleFromBorrowHandle(handleValue int32) *MessageHandle {
	handle := witRuntime.MakeHandle(handleValue)
	return &MessageHandle{handle}
}

// A fetched batch, and why it ended.
type FetchedBatch struct {
	Messages []*MessageHandle
	Stop     FetchStop
}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [resource-drop]pull-consumer
func resourceDropPullConsumer(handle int32)

// Pull-based consumer for batched, backpressure-friendly reads. The
// consumer must already exist on the stream — attach via `open-pull-consumer`.
type PullConsumer struct {
	handle *witRuntime.Handle
}

func (self *PullConsumer) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *PullConsumer) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *PullConsumer) Handle() int32 {
	return self.handle.Use()
}

func (self *PullConsumer) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropPullConsumer(handle)
	}
}

func PullConsumerFromOwnHandle(handleValue int32) *PullConsumer {
	handle := witRuntime.MakeHandle(handleValue)
	value := &PullConsumer{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropPullConsumer(handleValue)
		}
	}, 0)
	return value
}

func PullConsumerFromBorrowHandle(handleValue int32) *PullConsumer {
	handle := witRuntime.MakeHandle(handleValue)
	return &PullConsumer{handle}
}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [method]message-handle.message
func wasm_import_method_message_handle_message(arg0 int32, arg1 uintptr)

func (self *MessageHandle) Message() wasmcloud_nats_0_1_0_types.NatsMessage {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (10 * 4), 4))
	wasm_import_method_message_handle_message((self).Handle(), returnArea)
	value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	value0 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4))))

		option = witTypes.Some[string](value1)
	default:
		panic("unreachable")
	}
	var option4 witTypes.Option[[]wasmcloud_nats_0_1_0_types.HeaderEntry]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4)))) {
	case 0:

		option4 = witTypes.None[[]wasmcloud_nats_0_1_0_types.HeaderEntry]()
	case 1:
		result := make([]wasmcloud_nats_0_1_0_types.HeaderEntry, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (9 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (9 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 * 4))))), index*(4*4))
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

			result = append(result, wasmcloud_nats_0_1_0_types.HeaderEntry{Name: value2, Value: value3})
		}

		option4 = witTypes.Some[[]wasmcloud_nats_0_1_0_types.HeaderEntry](result)
	default:
		panic("unreachable")
	}
	result5 := wasmcloud_nats_0_1_0_types.NatsMessage{Subject: value, Body: value0, ReplyTo: option, Headers: option4}
	return result5

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [method]message-handle.sequence
func wasm_import_method_message_handle_sequence(arg0 int32) int64

func (self *MessageHandle) Sequence() uint64 {

	result := wasm_import_method_message_handle_sequence((self).Handle())
	return uint64(result)

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [method]message-handle.delivery-count
func wasm_import_method_message_handle_delivery_count(arg0 int32) int32

func (self *MessageHandle) DeliveryCount() uint32 {

	result := wasm_import_method_message_handle_delivery_count((self).Handle())
	return uint32(result)

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [async-lower][method]message-handle.ack
func wasm_import_method_message_handle_ack(arg0 int32, arg1 uintptr) int32

func (self *MessageHandle) Ack() witTypes.Result[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (40 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_message_handle_ack((self).Handle(), returnArea)))
	var result witTypes.Result[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError](witTypes.Unit{})
	case 1:
		var variant8 wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value0)

		case 2:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			var variant wasmcloud_nats_0_1_0_types.DeniedResource
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))) {
			case 0:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceSubject()

			case 1:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceStream()

			case 2:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceBucket()

			case 3:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceMessage(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 32))))

			default:
				panic("unreachable")
			}
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 40))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDenied(wasmcloud_nats_0_1_0_types.Denial{Reason: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), Target: variant, Name: value1})

		case 4:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorInvalidHeader(value2)

		case 6:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value3)

		case 7:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 8:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 9:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 10:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorLimitExceeded(value4)

		case 11:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value5)

		case 12:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value6)

		case 13:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 14:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAlreadySettled()

		case 15:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAckOwnedByHost()

		case 16:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value7)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError](variant8)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [async-lower][method]message-handle.ack-sync
func wasm_import_method_message_handle_ack_sync(arg0 int32, arg1 uintptr) int32

func (self *MessageHandle) AckSync() witTypes.Result[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (40 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_message_handle_ack_sync((self).Handle(), returnArea)))
	var result witTypes.Result[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError](witTypes.Unit{})
	case 1:
		var variant8 wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value0)

		case 2:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			var variant wasmcloud_nats_0_1_0_types.DeniedResource
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))) {
			case 0:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceSubject()

			case 1:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceStream()

			case 2:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceBucket()

			case 3:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceMessage(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 32))))

			default:
				panic("unreachable")
			}
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 40))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDenied(wasmcloud_nats_0_1_0_types.Denial{Reason: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), Target: variant, Name: value1})

		case 4:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorInvalidHeader(value2)

		case 6:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value3)

		case 7:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 8:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 9:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 10:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorLimitExceeded(value4)

		case 11:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value5)

		case 12:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value6)

		case 13:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 14:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAlreadySettled()

		case 15:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAckOwnedByHost()

		case 16:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value7)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError](variant8)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [async-lower][method]message-handle.nak
func wasm_import_method_message_handle_nak(arg0 int32, arg1 int32, arg2 int32, arg3 uintptr) int32

func (self *MessageHandle) Nak(delayMs witTypes.Option[uint32]) witTypes.Result[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (40 + 2*4), 8))
	var option int32
	var option0 int32
	switch delayMs.Tag() {
	case witTypes.OptionNone:

		option = int32(0)
		option0 = 0
	case witTypes.OptionSome:
		payload := delayMs.Some()

		option = int32(1)
		option0 = int32(payload)
	default:
		panic("unreachable")
	}

	witAsync.SubtaskWait(uint32(wasm_import_method_message_handle_nak((self).Handle(), option, option0, returnArea)))
	var result witTypes.Result[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError](witTypes.Unit{})
	case 1:
		var variant9 wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value)

		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value1)

		case 2:

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			var variant wasmcloud_nats_0_1_0_types.DeniedResource
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))) {
			case 0:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceSubject()

			case 1:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceStream()

			case 2:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceBucket()

			case 3:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceMessage(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 32))))

			default:
				panic("unreachable")
			}
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 40))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDenied(wasmcloud_nats_0_1_0_types.Denial{Reason: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), Target: variant, Name: value2})

		case 4:

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorInvalidHeader(value3)

		case 6:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value4)

		case 7:

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 8:

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 9:

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 10:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorLimitExceeded(value5)

		case 11:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value6)

		case 12:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value7)

		case 13:

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 14:

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAlreadySettled()

		case 15:

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAckOwnedByHost()

		case 16:
			value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value8)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError](variant9)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [async-lower][method]message-handle.in-progress
func wasm_import_method_message_handle_in_progress(arg0 int32, arg1 uintptr) int32

func (self *MessageHandle) InProgress() witTypes.Result[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (40 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_message_handle_in_progress((self).Handle(), returnArea)))
	var result witTypes.Result[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError](witTypes.Unit{})
	case 1:
		var variant8 wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value0)

		case 2:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			var variant wasmcloud_nats_0_1_0_types.DeniedResource
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))) {
			case 0:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceSubject()

			case 1:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceStream()

			case 2:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceBucket()

			case 3:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceMessage(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 32))))

			default:
				panic("unreachable")
			}
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 40))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDenied(wasmcloud_nats_0_1_0_types.Denial{Reason: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), Target: variant, Name: value1})

		case 4:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorInvalidHeader(value2)

		case 6:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value3)

		case 7:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 8:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 9:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 10:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorLimitExceeded(value4)

		case 11:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value5)

		case 12:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value6)

		case 13:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 14:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAlreadySettled()

		case 15:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAckOwnedByHost()

		case 16:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value7)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError](variant8)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [async-lower][method]message-handle.term
func wasm_import_method_message_handle_term(arg0 int32, arg1 uintptr) int32

func (self *MessageHandle) Term() witTypes.Result[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (40 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_message_handle_term((self).Handle(), returnArea)))
	var result witTypes.Result[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError](witTypes.Unit{})
	case 1:
		var variant8 wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value0)

		case 2:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			var variant wasmcloud_nats_0_1_0_types.DeniedResource
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))) {
			case 0:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceSubject()

			case 1:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceStream()

			case 2:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceBucket()

			case 3:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceMessage(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 32))))

			default:
				panic("unreachable")
			}
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 40))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDenied(wasmcloud_nats_0_1_0_types.Denial{Reason: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), Target: variant, Name: value1})

		case 4:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorInvalidHeader(value2)

		case 6:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value3)

		case 7:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 8:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 9:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 10:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorLimitExceeded(value4)

		case 11:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value5)

		case 12:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value6)

		case 13:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 14:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAlreadySettled()

		case 15:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAckOwnedByHost()

		case 16:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value7)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError](variant8)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [async-lower][method]pull-consumer.fetch
func wasm_import_method_pull_consumer_fetch(arg0 int32, arg1 int32, arg2 int32, arg3 uintptr) int32

func (self *PullConsumer) Fetch(batch uint32, timeoutMs uint32) witTypes.Result[FetchedBatch, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (40 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_pull_consumer_fetch((self).Handle(), int32(batch), int32(timeoutMs), returnArea)))
	var result9 witTypes.Result[FetchedBatch, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result := make([]*MessageHandle, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), index*4)

			result = append(result, MessageHandleFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(base), 0))))))
		}

		result9 = witTypes.Ok[FetchedBatch, wasmcloud_nats_0_1_0_types.NatsError](FetchedBatch{Messages: result, Stop: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4)))))})
	case 1:
		var variant8 wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value0)

		case 2:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			var variant wasmcloud_nats_0_1_0_types.DeniedResource
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))) {
			case 0:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceSubject()

			case 1:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceStream()

			case 2:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceBucket()

			case 3:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceMessage(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 32))))

			default:
				panic("unreachable")
			}
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 40))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDenied(wasmcloud_nats_0_1_0_types.Denial{Reason: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), Target: variant, Name: value1})

		case 4:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorInvalidHeader(value2)

		case 6:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value3)

		case 7:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 8:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 9:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 10:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorLimitExceeded(value4)

		case 11:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value5)

		case 12:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value6)

		case 13:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 14:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAlreadySettled()

		case 15:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAckOwnedByHost()

		case 16:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value7)

		default:
			panic("unreachable")
		}

		result9 = witTypes.Err[FetchedBatch, wasmcloud_nats_0_1_0_types.NatsError](variant8)
	default:
		panic("unreachable")
	}

	return result9

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [async-lower][method]pull-consumer.fetch-with-limits
func wasm_import_method_pull_consumer_fetch_with_limits(arg0 int32, arg1 int32, arg2 int64, arg3 int32, arg4 uintptr) int32

func (self *PullConsumer) FetchWithLimits(batch uint32, maxBytes uint64, timeoutMs uint32) witTypes.Result[FetchedBatch, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (40 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_pull_consumer_fetch_with_limits((self).Handle(), int32(batch), int64(maxBytes), int32(timeoutMs), returnArea)))
	var result9 witTypes.Result[FetchedBatch, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result := make([]*MessageHandle, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), index*4)

			result = append(result, MessageHandleFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(base), 0))))))
		}

		result9 = witTypes.Ok[FetchedBatch, wasmcloud_nats_0_1_0_types.NatsError](FetchedBatch{Messages: result, Stop: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4)))))})
	case 1:
		var variant8 wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value0)

		case 2:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			var variant wasmcloud_nats_0_1_0_types.DeniedResource
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))) {
			case 0:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceSubject()

			case 1:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceStream()

			case 2:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceBucket()

			case 3:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceMessage(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 32))))

			default:
				panic("unreachable")
			}
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 40))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDenied(wasmcloud_nats_0_1_0_types.Denial{Reason: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), Target: variant, Name: value1})

		case 4:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorInvalidHeader(value2)

		case 6:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value3)

		case 7:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 8:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 9:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 10:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorLimitExceeded(value4)

		case 11:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value5)

		case 12:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value6)

		case 13:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 14:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAlreadySettled()

		case 15:

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAckOwnedByHost()

		case 16:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant8 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value7)

		default:
			panic("unreachable")
		}

		result9 = witTypes.Err[FetchedBatch, wasmcloud_nats_0_1_0_types.NatsError](variant8)
	default:
		panic("unreachable")
	}

	return result9

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [async-lower][method]pull-consumer.info
func wasm_import_method_pull_consumer_info(arg0 int32, arg1 uintptr) int32

func (self *PullConsumer) Info() witTypes.Result[ConsumerInfo, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (80 + 8*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_pull_consumer_info((self).Handle(), returnArea)))
	var result13 witTypes.Result[ConsumerInfo, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))
		value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 3*4))))
		value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 4*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 5*4))))
		result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 7*4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 7*4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 6*4))))), index*(2*4))
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, value2)
		}

		result13 = witTypes.Ok[ConsumerInfo, wasmcloud_nats_0_1_0_types.NatsError](ConsumerInfo{Name: value, StreamName: value0, FilterSubject: value1, FilterSubjects: result, MaxAckPending: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 8*4)))), MaxWaiting: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 8*4)))), MaxRequestBatch: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 8*4)))), MaxRequestMaxBytes: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (32 + 8*4)))), MaxDeliver: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 8*4)))), AckWaitMs: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 8*4)))), NumAckPending: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (56 + 8*4)))), NumPending: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (64 + 8*4)))), NumRedelivered: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (72 + 8*4))))})
	case 1:
		var variant12 wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value3)

		case 1:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value4)

		case 2:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			var variant wasmcloud_nats_0_1_0_types.DeniedResource
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))) {
			case 0:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceSubject()

			case 1:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceStream()

			case 2:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceBucket()

			case 3:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceMessage(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 32))))

			default:
				panic("unreachable")
			}
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 40))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDenied(wasmcloud_nats_0_1_0_types.Denial{Reason: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), Target: variant, Name: value5})

		case 4:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorInvalidHeader(value6)

		case 6:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value7)

		case 7:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 8:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 9:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 10:
			value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorLimitExceeded(value8)

		case 11:
			value9 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value9)

		case 12:
			value10 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value10)

		case 13:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 14:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAlreadySettled()

		case 15:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAckOwnedByHost()

		case 16:
			value11 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value11)

		default:
			panic("unreachable")
		}

		result13 = witTypes.Err[ConsumerInfo, wasmcloud_nats_0_1_0_types.NatsError](variant12)
	default:
		panic("unreachable")
	}

	return result13

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [async-lower]publish
func wasm_import_publish(arg0 uintptr, arg1 uintptr) int32

func Publish(msg wasmcloud_nats_0_1_0_types.NatsMessage) witTypes.Result[PublishAck, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (40 + 2*4), 8))
	params := witRuntime.Allocate(pinner, (10 * 4), 4)
	utf8 := unsafe.Pointer(unsafe.StringData((msg).Subject))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 4)) = uint32(uint32(len((msg).Subject)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 0)) = uint32(uintptr(uintptr(utf8)))
	data := unsafe.Pointer(unsafe.SliceData((msg).Body))
	pinner.Pin(data)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (3 * 4))) = uint32(uint32(len((msg).Body)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (2 * 4))) = uint32(uintptr(uintptr(data)))

	switch (msg).ReplyTo.Tag() {
	case witTypes.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (4 * 4))) = int8(int32(0))

	case witTypes.OptionSome:
		payload := (msg).ReplyTo.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (4 * 4))) = int8(int32(1))
		utf80 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf80)
		*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (6 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (5 * 4))) = uint32(uintptr(uintptr(utf80)))

	default:
		panic("unreachable")
	}

	switch (msg).Headers.Tag() {
	case witTypes.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (7 * 4))) = int8(int32(0))

	case witTypes.OptionSome:
		payload := (msg).Headers.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (7 * 4))) = int8(int32(1))
		slice := payload
		length := uint32(len(slice))
		result := witRuntime.Allocate(pinner, uintptr(length*(4*4)), 4)
		for index, element := range slice {
			base := unsafe.Add(result, index*(4*4))
			utf81 := unsafe.Pointer(unsafe.StringData((element).Name))
			pinner.Pin(utf81)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).Name)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf81)))
			utf82 := unsafe.Pointer(unsafe.StringData((element).Value))
			pinner.Pin(utf82)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = uint32(uint32(len((element).Value)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uintptr(uintptr(utf82)))

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (9 * 4))) = uint32(length)
		*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (8 * 4))) = uint32(uintptr(uintptr(result)))

	default:
		panic("unreachable")
	}

	witAsync.SubtaskWait(uint32(wasm_import_publish(uintptr(params), returnArea)))
	var result13 witTypes.Result[PublishAck, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))

		result13 = witTypes.Ok[PublishAck, wasmcloud_nats_0_1_0_types.NatsError](PublishAck{StreamName: value, Sequence: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4)))), Duplicate: (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 2*4)))) != 0)})
	case 1:
		var variant12 wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value3)

		case 1:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value4)

		case 2:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			var variant wasmcloud_nats_0_1_0_types.DeniedResource
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))) {
			case 0:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceSubject()

			case 1:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceStream()

			case 2:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceBucket()

			case 3:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceMessage(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 32))))

			default:
				panic("unreachable")
			}
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 40))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDenied(wasmcloud_nats_0_1_0_types.Denial{Reason: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), Target: variant, Name: value5})

		case 4:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorInvalidHeader(value6)

		case 6:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value7)

		case 7:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 8:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 9:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 10:
			value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorLimitExceeded(value8)

		case 11:
			value9 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value9)

		case 12:
			value10 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value10)

		case 13:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 14:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAlreadySettled()

		case 15:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAckOwnedByHost()

		case 16:
			value11 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value11)

		default:
			panic("unreachable")
		}

		result13 = witTypes.Err[PublishAck, wasmcloud_nats_0_1_0_types.NatsError](variant12)
	default:
		panic("unreachable")
	}

	return result13

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [async-lower]get-by-sequence
func wasm_import_get_by_sequence(arg0 uintptr, arg1 uint32, arg2 int64, arg3 uintptr) int32

func GetBySequence(streamName string, sequence uint64) witTypes.Result[StoredMessage, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (24 + 6*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(streamName))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_get_by_sequence(uintptr(utf8), uint32(len(streamName)), int64(sequence), returnArea)))
	var result13 witTypes.Result[StoredMessage, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))
		value0 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 3*4))))
		var option witTypes.Option[[]wasmcloud_nats_0_1_0_types.HeaderEntry]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 4*4)))) {
		case 0:

			option = witTypes.None[[]wasmcloud_nats_0_1_0_types.HeaderEntry]()
		case 1:
			result := make([]wasmcloud_nats_0_1_0_types.HeaderEntry, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 6*4))))
			for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 6*4)))); index++ {
				base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 5*4))))), index*(4*4))
				value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
				value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

				result = append(result, wasmcloud_nats_0_1_0_types.HeaderEntry{Name: value1, Value: value2})
			}

			option = witTypes.Some[[]wasmcloud_nats_0_1_0_types.HeaderEntry](result)
		default:
			panic("unreachable")
		}

		result13 = witTypes.Ok[StoredMessage, wasmcloud_nats_0_1_0_types.NatsError](StoredMessage{Subject: value, Sequence: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4)))), Data: value0, Headers: option})
	case 1:
		var variant12 wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value3)

		case 1:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value4)

		case 2:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			var variant wasmcloud_nats_0_1_0_types.DeniedResource
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))) {
			case 0:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceSubject()

			case 1:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceStream()

			case 2:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceBucket()

			case 3:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceMessage(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 32))))

			default:
				panic("unreachable")
			}
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 40))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDenied(wasmcloud_nats_0_1_0_types.Denial{Reason: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), Target: variant, Name: value5})

		case 4:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorInvalidHeader(value6)

		case 6:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value7)

		case 7:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 8:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 9:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 10:
			value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorLimitExceeded(value8)

		case 11:
			value9 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value9)

		case 12:
			value10 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value10)

		case 13:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 14:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAlreadySettled()

		case 15:

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAckOwnedByHost()

		case 16:
			value11 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant12 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value11)

		default:
			panic("unreachable")
		}

		result13 = witTypes.Err[StoredMessage, wasmcloud_nats_0_1_0_types.NatsError](variant12)
	default:
		panic("unreachable")
	}

	return result13

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [async-lower]scan
func wasm_import_scan(arg0 uintptr, arg1 uint32, arg2 int64, arg3 int32, arg4 uintptr) int32

func Scan(streamName string, startSequence uint64, maxCount uint32) witTypes.Result[[]StoredMessage, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (40 + 2*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(streamName))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_scan(uintptr(utf8), uint32(len(streamName)), int64(startSequence), int32(maxCount), returnArea)))
	var result14 witTypes.Result[[]StoredMessage, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result3 := make([]StoredMessage, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), index*(16+6*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
			value0 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4))))
			var option witTypes.Option[[]wasmcloud_nats_0_1_0_types.HeaderEntry]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4)))) {
			case 0:

				option = witTypes.None[[]wasmcloud_nats_0_1_0_types.HeaderEntry]()
			case 1:
				result := make([]wasmcloud_nats_0_1_0_types.HeaderEntry, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 6*4))))
				for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 6*4)))); index++ {
					base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 5*4))))), index*(4*4))
					value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
					value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

					result = append(result, wasmcloud_nats_0_1_0_types.HeaderEntry{Name: value1, Value: value2})
				}

				option = witTypes.Some[[]wasmcloud_nats_0_1_0_types.HeaderEntry](result)
			default:
				panic("unreachable")
			}

			result3 = append(result3, StoredMessage{Subject: value, Sequence: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))), Data: value0, Headers: option})
		}

		result14 = witTypes.Ok[[]StoredMessage, wasmcloud_nats_0_1_0_types.NatsError](result3)
	case 1:
		var variant13 wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value4)

		case 1:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value5)

		case 2:

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			var variant wasmcloud_nats_0_1_0_types.DeniedResource
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))) {
			case 0:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceSubject()

			case 1:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceStream()

			case 2:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceBucket()

			case 3:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceMessage(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 32))))

			default:
				panic("unreachable")
			}
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 40))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDenied(wasmcloud_nats_0_1_0_types.Denial{Reason: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), Target: variant, Name: value6})

		case 4:

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorInvalidHeader(value7)

		case 6:
			value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value8)

		case 7:

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 8:

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 9:

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 10:
			value9 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorLimitExceeded(value9)

		case 11:
			value10 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value10)

		case 12:
			value11 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value11)

		case 13:

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 14:

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAlreadySettled()

		case 15:

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAckOwnedByHost()

		case 16:
			value12 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value12)

		default:
			panic("unreachable")
		}

		result14 = witTypes.Err[[]StoredMessage, wasmcloud_nats_0_1_0_types.NatsError](variant13)
	default:
		panic("unreachable")
	}

	return result14

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [async-lower]open-pull-consumer
func wasm_import_open_pull_consumer(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr) int32

func OpenPullConsumer(streamName string, consumer string) witTypes.Result[*PullConsumer, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (40 + 2*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(streamName))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(consumer))
	pinner.Pin(utf80)

	witAsync.SubtaskWait(uint32(wasm_import_open_pull_consumer(uintptr(utf8), uint32(len(streamName)), uintptr(utf80), uint32(len(consumer)), returnArea)))
	var result witTypes.Result[*PullConsumer, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*PullConsumer, wasmcloud_nats_0_1_0_types.NatsError](PullConsumerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))))
	case 1:
		var variant9 wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value)

		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value1)

		case 2:

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			var variant wasmcloud_nats_0_1_0_types.DeniedResource
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))) {
			case 0:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceSubject()

			case 1:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceStream()

			case 2:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceBucket()

			case 3:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceMessage(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 32))))

			default:
				panic("unreachable")
			}
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 40))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDenied(wasmcloud_nats_0_1_0_types.Denial{Reason: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), Target: variant, Name: value2})

		case 4:

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorInvalidHeader(value3)

		case 6:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value4)

		case 7:

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 8:

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 9:

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 10:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorLimitExceeded(value5)

		case 11:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value6)

		case 12:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value7)

		case 13:

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 14:

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAlreadySettled()

		case 15:

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAckOwnedByHost()

		case 16:
			value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant9 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value8)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*PullConsumer, wasmcloud_nats_0_1_0_types.NatsError](variant9)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [async-lower]get-stream-info
func wasm_import_get_stream_info(arg0 uintptr, arg1 uint32, arg2 uintptr) int32

func GetStreamInfo(streamName string) witTypes.Result[StreamInfo, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (48 + 4*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(streamName))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_get_stream_info(uintptr(utf8), uint32(len(streamName)), returnArea)))
	var result11 witTypes.Result[StreamInfo, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))
		result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 3*4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 3*4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))), index*(2*4))
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, value0)
		}

		result11 = witTypes.Ok[StreamInfo, wasmcloud_nats_0_1_0_types.NatsError](StreamInfo{Name: value, Subjects: result, Messages: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 4*4)))), Bytes: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 4*4)))), FirstSequence: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 4*4)))), LastSequence: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (32 + 4*4)))), ConsumerCount: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 4*4))))})
	case 1:
		var variant10 wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value1)

		case 1:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value2)

		case 2:

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			var variant wasmcloud_nats_0_1_0_types.DeniedResource
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))) {
			case 0:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceSubject()

			case 1:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceStream()

			case 2:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceBucket()

			case 3:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceMessage(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 32))))

			default:
				panic("unreachable")
			}
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 40))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDenied(wasmcloud_nats_0_1_0_types.Denial{Reason: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), Target: variant, Name: value3})

		case 4:

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorInvalidHeader(value4)

		case 6:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value5)

		case 7:

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 8:

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 9:

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 10:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorLimitExceeded(value6)

		case 11:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value7)

		case 12:
			value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value8)

		case 13:

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 14:

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAlreadySettled()

		case 15:

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAckOwnedByHost()

		case 16:
			value9 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value9)

		default:
			panic("unreachable")
		}

		result11 = witTypes.Err[StreamInfo, wasmcloud_nats_0_1_0_types.NatsError](variant10)
	default:
		panic("unreachable")
	}

	return result11

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [async-lower]list-stream-subjects
func wasm_import_list_stream_subjects(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr) int32

func ListStreamSubjects(streamName string, subjectFilter string) witTypes.Result[[]SubjectCount, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (40 + 2*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(streamName))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(subjectFilter))
	pinner.Pin(utf80)

	witAsync.SubtaskWait(uint32(wasm_import_list_stream_subjects(uintptr(utf8), uint32(len(streamName)), uintptr(utf80), uint32(len(subjectFilter)), returnArea)))
	var result11 witTypes.Result[[]SubjectCount, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result := make([]SubjectCount, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), index*(8+2*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, SubjectCount{Subject: value, Count: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(base), (2 * 4))))})
		}

		result11 = witTypes.Ok[[]SubjectCount, wasmcloud_nats_0_1_0_types.NatsError](result)
	case 1:
		var variant10 wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value1)

		case 1:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value2)

		case 2:

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			var variant wasmcloud_nats_0_1_0_types.DeniedResource
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))) {
			case 0:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceSubject()

			case 1:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceStream()

			case 2:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceBucket()

			case 3:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceMessage(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 32))))

			default:
				panic("unreachable")
			}
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 40))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDenied(wasmcloud_nats_0_1_0_types.Denial{Reason: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), Target: variant, Name: value3})

		case 4:

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorInvalidHeader(value4)

		case 6:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value5)

		case 7:

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 8:

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 9:

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 10:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorLimitExceeded(value6)

		case 11:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value7)

		case 12:
			value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value8)

		case 13:

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 14:

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAlreadySettled()

		case 15:

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAckOwnedByHost()

		case 16:
			value9 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant10 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value9)

		default:
			panic("unreachable")
		}

		result11 = witTypes.Err[[]SubjectCount, wasmcloud_nats_0_1_0_types.NatsError](variant10)
	default:
		panic("unreachable")
	}

	return result11

}

//go:wasmimport wasmcloud:nats/jetstream@0.1.0 [async-lower]get-consumer-info
func wasm_import_get_consumer_info(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr) int32

func GetConsumerInfo(streamName string, consumer string) witTypes.Result[ConsumerInfo, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (80 + 8*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(streamName))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(consumer))
	pinner.Pin(utf80)

	witAsync.SubtaskWait(uint32(wasm_import_get_consumer_info(uintptr(utf8), uint32(len(streamName)), uintptr(utf80), uint32(len(consumer)), returnArea)))
	var result14 witTypes.Result[ConsumerInfo, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))
		value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 3*4))))
		value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 4*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 5*4))))
		result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 7*4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 7*4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 6*4))))), index*(2*4))
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, value3)
		}

		result14 = witTypes.Ok[ConsumerInfo, wasmcloud_nats_0_1_0_types.NatsError](ConsumerInfo{Name: value, StreamName: value1, FilterSubject: value2, FilterSubjects: result, MaxAckPending: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 8*4)))), MaxWaiting: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 8*4)))), MaxRequestBatch: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 8*4)))), MaxRequestMaxBytes: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (32 + 8*4)))), MaxDeliver: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 8*4)))), AckWaitMs: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 8*4)))), NumAckPending: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (56 + 8*4)))), NumPending: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (64 + 8*4)))), NumRedelivered: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (72 + 8*4))))})
	case 1:
		var variant13 wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value4)

		case 1:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value5)

		case 2:

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			var variant wasmcloud_nats_0_1_0_types.DeniedResource
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))) {
			case 0:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceSubject()

			case 1:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceStream()

			case 2:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceBucket()

			case 3:

				variant = wasmcloud_nats_0_1_0_types.MakeDeniedResourceMessage(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 32))))

			default:
				panic("unreachable")
			}
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 40))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDenied(wasmcloud_nats_0_1_0_types.Denial{Reason: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), Target: variant, Name: value6})

		case 4:

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorInvalidHeader(value7)

		case 6:
			value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value8)

		case 7:

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 8:

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 9:

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 10:
			value9 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorLimitExceeded(value9)

		case 11:
			value10 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value10)

		case 12:
			value11 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value11)

		case 13:

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 14:

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAlreadySettled()

		case 15:

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorAckOwnedByHost()

		case 16:
			value12 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant13 = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value12)

		default:
			panic("unreachable")
		}

		result14 = witTypes.Err[ConsumerInfo, wasmcloud_nats_0_1_0_types.NatsError](variant13)
	default:
		panic("unreachable")
	}

	return result14

}
