// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.0.0
//     wasmcloud:keyvalue@0.1.0
//     wasmcloud:messaging@0.2.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_secrets_2_0_0_reveal

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"go.wasmcloud.dev/component/imports/wasmcloud_secrets_2_0_0_store"
	"runtime"
	"unsafe"
)

type Secret = wasmcloud_secrets_2_0_0_store.Secret
type SecretValue = wasmcloud_secrets_2_0_0_store.SecretValue

//go:wasmimport wasmcloud:secrets/reveal@2.0.0 [async-lower]reveal
func wasm_import_reveal(arg0 int32, arg1 uintptr) int32

func Reveal(s *wasmcloud_secrets_2_0_0_store.Secret) wasmcloud_secrets_2_0_0_store.SecretValue {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_reveal((s).Handle(), returnArea)))
	var variant wasmcloud_secrets_2_0_0_store.SecretValue
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		variant = wasmcloud_secrets_2_0_0_store.MakeSecretValueString(value)

	case 1:
		value0 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		variant = wasmcloud_secrets_2_0_0_store.MakeSecretValueBytes(value0)

	default:
		panic("unreachable")
	}

	return variant

}
