// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:component-go@0.2.0
//     componentize-go:union

package wasi_cli_0_2_8_stderr

import (
	"go.wasmcloud.dev/component/imports/wasi_io_0_2_8_streams"
)

type OutputStream = wasi_io_0_2_8_streams.OutputStream

//go:wasmimport wasi:cli/stderr@0.2.8 get-stderr
func wasm_import_get_stderr() int32

func GetStderr() *wasi_io_0_2_8_streams.OutputStream {

	result := wasm_import_get_stderr()
	return wasi_io_0_2_8_streams.OutputStreamFromOwnHandle(int32(uintptr(result)))

}
