// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:component-go@0.2.0
//     componentize-go:union

package wasi_cli_0_2_8_terminal_stdin

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"go.wasmcloud.dev/component/imports/wasi_cli_0_2_8_terminal_input"
	"runtime"
	"unsafe"
)

type TerminalInput = wasi_cli_0_2_8_terminal_input.TerminalInput

//go:wasmimport wasi:cli/terminal-stdin@0.2.8 get-terminal-stdin
func wasm_import_get_terminal_stdin(arg0 uintptr)

func GetTerminalStdin() witTypes.Option[*wasi_cli_0_2_8_terminal_input.TerminalInput] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	wasm_import_get_terminal_stdin(returnArea)
	var option witTypes.Option[*wasi_cli_0_2_8_terminal_input.TerminalInput]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[*wasi_cli_0_2_8_terminal_input.TerminalInput]()
	case 1:

		option = witTypes.Some[*wasi_cli_0_2_8_terminal_input.TerminalInput](wasi_cli_0_2_8_terminal_input.TerminalInputFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	default:
		panic("unreachable")
	}
	result := option
	return result

}
