// Generated by `wit-bindgen` 0.61.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.1.0
//     wasmcloud:keyvalue@0.2.0
//     wasmcloud:messaging@0.3.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_messaging_0_3_0_types

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

// A message sent to or received from a broker.
//
// The body is a `stream<u8>`: the payload flows incrementally on both the producing and the
// consuming side, so neither end is required to hold it whole in memory. Hosts whose backend
// cannot stream a message (e.g. core NATS, which sends a message as one bounded payload) MAY
// buffer a body internally before forwarding it — the interface permits streaming without
// requiring every backend to provide it, and a backend that can fan a stream out efficiently
// pays no buffering cost.
type BrokerMessage struct {
	Subject string
	Body    *witTypes.StreamReader[uint8]
	ReplyTo witTypes.Option[string]
}

const (
	// The subject is malformed, empty, or otherwise rejected by the broker.
	ErrorSubjectInvalid uint8 = 0
	// The requesting component is not permitted to publish to this subject.
	ErrorAccessDenied uint8 = 1
	// A `request` did not receive a reply within its `timeout-ms`.
	ErrorTimeout uint8 = 2
	// The broker is currently unreachable or otherwise unavailable. The operation
	// may succeed if retried later.
	ErrorBrokerUnavailable uint8 = 3
	// The message body exceeded the broker's maximum payload size.
	ErrorMessageTooLarge uint8 = 4
	// The operation was rejected because a quota or rate limit was exceeded.
	ErrorQuotaExceeded uint8 = 5
	// Some other implementation-specific error has occurred (e.g. I/O). Used for
	// backend-specific failures that do not map to a named case above.
	ErrorOther uint8 = 6
)

// The set of errors which may be raised by broker operations (the `consumer` interface).
type Error struct {
	tag   uint8
	value any
}

func (self Error) Tag() uint8 {
	return self.tag
}

func (self Error) Other() string {
	if self.tag != ErrorOther {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeErrorSubjectInvalid() Error {
	return Error{ErrorSubjectInvalid, nil}
}
func MakeErrorAccessDenied() Error {
	return Error{ErrorAccessDenied, nil}
}
func MakeErrorTimeout() Error {
	return Error{ErrorTimeout, nil}
}
func MakeErrorBrokerUnavailable() Error {
	return Error{ErrorBrokerUnavailable, nil}
}
func MakeErrorMessageTooLarge() Error {
	return Error{ErrorMessageTooLarge, nil}
}
func MakeErrorQuotaExceeded() Error {
	return Error{ErrorQuotaExceeded, nil}
}
func MakeErrorOther(value string) Error {
	return Error{ErrorOther, value}
}

const (
	// The message cannot be processed, and redelivering the same message will
	// not help (malformed payload, unrecognized subject shape, ...).
	HandleMessageErrorReject uint8 = 0
	// Processing failed transiently; redelivering the message later may succeed
	// (e.g. a downstream dependency was briefly unavailable).
	HandleMessageErrorRetry uint8 = 1
	// Some other handler-specific failure, with detail. Hosts treat it as
	// `reject` for redelivery purposes.
	HandleMessageErrorOther uint8 = 2
)

// The disposition a message handler reports for a delivery it could not process.
//
// Hosts currently record the disposition; backends with redelivery semantics
// (e.g. NATS JetStream) can map `retry` to a negative acknowledgement and
// `reject` to a terminal one.
type HandleMessageError struct {
	tag   uint8
	value any
}

func (self HandleMessageError) Tag() uint8 {
	return self.tag
}

func (self HandleMessageError) Other() string {
	if self.tag != HandleMessageErrorOther {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeHandleMessageErrorReject() HandleMessageError {
	return HandleMessageError{HandleMessageErrorReject, nil}
}
func MakeHandleMessageErrorRetry() HandleMessageError {
	return HandleMessageError{HandleMessageErrorRetry, nil}
}
func MakeHandleMessageErrorOther(value string) HandleMessageError {
	return HandleMessageError{HandleMessageErrorOther, value}
}
