// Generated by `wit-bindgen` 0.61.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasmcloud:host@0.1.3
//     wasmcloud:plugin-go@0.1.0
//     componentize-go:union

package wasmcloud_host_0_1_3_workload_lifecycle

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

type WorkloadId = string
type ComponentId = string

// Semantic version of an interface instance (e.g. `0.2.0-draft`).
type Version struct {
	Major uint64
	Minor uint64
	Patch uint64
	// Pre-release identifier, if any (e.g. `draft`, `rc.1`).
	Pre witTypes.Option[string]
	// Build metadata, if any.
	Build witTypes.Option[string]
}

// One interface instance the workload matched on this plugin — e.g. the
// `store` interface of `acme:kv@0.1.0`, labeled `cache`, with its
// manifest config.
type InterfaceBinding struct {
	// Interface namespace (e.g. `acme`).
	Namespace string
	// Package within the namespace (e.g. `kv`).
	Package string
	// The matched interface names within the package (e.g. `store`).
	Interfaces []string
	// Version of the instance, if one was requested.
	Version witTypes.Option[Version]
	// Instance label when the workload names multiple instances of the
	// same namespace:package, if any. Component-facing: what the component
	// calls this import.
	//
	// Two gaps for a **wasm** host component plugin specifically (a
	// Rust built-in plugin doesn't have either): a workload with more
	// than one *named* binding on the same namespace:package is
	// rejected before bind unless the plugin implements
	// `supports_named_instances()` — no wasm plugin can opt into that
	// today, so this field only ever arrives as at most one populated
	// `name` per namespace:package per workload in practice. And even
	// where it is populated, it reaches `on-workload-bind` but is not
	// threaded through to the capability call itself — nothing on a
	// later `store.get`-style call says which binding it's for, only
	// `wasmcloud:host/identity`'s workload/component id. A plugin that
	// needs to serve two *unnamed* bindings of the same
	// namespace:package differently has no way to disambiguate them at
	// all today.
	Name witTypes.Option[string]
	// Platform-facing id the binding was declared with, if any — what the
	// platform's configuration calls the same instance.
	//
	// Two names, one contract: `name` above and `external-id` here are the
	// two names an instance can carry, and both refer to the one interface
	// contract described by the rest of this record. An external-id is not
	// an identity — it carries no uniqueness requirement, and a binding may
	// declare either name, both, or neither.
	ExternalId witTypes.Option[string]
	// Interface-level configuration from the workload manifest, as
	// key/value pairs sorted by key.
	Config []witTypes.Tuple2[string, string]
}

// Identity and configuration of a workload binding to this plugin.
type WorkloadInfo struct {
	// Unique id of the workload instance.
	Id string
	// Human-readable workload name.
	Name string
	// Namespace the workload was deployed under.
	Namespace string
	// Id of the workload's service, if it has one. A service is the
	// workload's long-lived item; it can make capability calls just as a
	// component can, so this id also appears as `identity.get-component-id`
	// on calls the service makes.
	Service witTypes.Option[string]
	// Ids of the workload's components, excluding the service above.
	Components []string
	// Every interface instance the workload matched on this plugin.
	Interfaces []InterfaceBinding
}
