// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.0.0
//     wasmcloud:keyvalue@0.1.0
//     wasmcloud:messaging@0.2.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_blobstore_0_1_0_types

import ()

// name of a container, a collection of objects.
// The container name may be any valid UTF-8 string.
type ContainerName = string

// name of an object within a container
// The object name may be any valid UTF-8 string.
type ObjectName = string

// nanoseconds since the Unix epoch.
type Timestamp = uint64

// size of an object, in bytes
type ObjectSize = uint64

const (
	// The referenced container does not exist.
	ErrorNoSuchContainer uint8 = 0
	// A container with the requested name already exists (e.g. on
	// `create-container`).
	ErrorContainerAlreadyExists uint8 = 1
	// The referenced object does not exist.
	ErrorNoSuchObject uint8 = 2
	// The requesting component does not have access to the container or
	// object (which may or may not exist).
	ErrorAccessDenied uint8 = 3
	// The operation did not complete within the host- or backend-imposed
	// time limit.
	ErrorTimeout uint8 = 4
	// The store is currently unreachable or otherwise unavailable. The
	// operation may succeed if retried later.
	ErrorStoreUnavailable uint8 = 5
	// The operation was rejected because a storage quota or rate limit was
	// exceeded.
	ErrorQuotaExceeded uint8 = 6
	// Some other implementation-specific error has occurred (e.g. I/O). Used
	// for backend-specific failures that do not map to a named case above.
	ErrorOther uint8 = 7
)

// The set of errors which may be raised by functions in this package.
//
// Following the wasip3 convention, this enumerates specific named cases
// rather than a bare `string`. It is intentionally non-exhaustive: future
// versions may add cases, and generated bindings are marked non-exhaustive
// accordingly, so consumers must always include a catch-all arm.
// Backend-specific failures that do not map to a named case are reported
// via `other`.
type Error struct {
	tag   uint8
	value any
}

func (self Error) Tag() uint8 {
	return self.tag
}

func (self Error) Other() string {
	if self.tag != ErrorOther {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeErrorNoSuchContainer() Error {
	return Error{ErrorNoSuchContainer, nil}
}
func MakeErrorContainerAlreadyExists() Error {
	return Error{ErrorContainerAlreadyExists, nil}
}
func MakeErrorNoSuchObject() Error {
	return Error{ErrorNoSuchObject, nil}
}
func MakeErrorAccessDenied() Error {
	return Error{ErrorAccessDenied, nil}
}
func MakeErrorTimeout() Error {
	return Error{ErrorTimeout, nil}
}
func MakeErrorStoreUnavailable() Error {
	return Error{ErrorStoreUnavailable, nil}
}
func MakeErrorQuotaExceeded() Error {
	return Error{ErrorQuotaExceeded, nil}
}
func MakeErrorOther(value string) Error {
	return Error{ErrorOther, value}
}

// information about a container
type ContainerMetadata struct {
	// the container's name
	Name string
	// date and time the container was created
	CreatedAt uint64
}

// information about an object
type ObjectMetadata struct {
	// the object's name
	Name string
	// the object's parent container
	Container string
	// date and time the object was created
	CreatedAt uint64
	// size of the object, in bytes
	Size uint64
}

// identifier for an object that includes its container name
type ObjectId struct {
	Container string
	Object    string
}
