// Generated by `wit-bindgen` 0.61.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.1.0
//     wasmcloud:keyvalue@0.2.0
//     wasmcloud:messaging@0.3.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_messaging_0_3_0_handler

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"go.wasmcloud.dev/component/imports/wasmcloud_messaging_0_3_0_types"
	"unsafe"
)

type BrokerMessage = wasmcloud_messaging_0_3_0_types.BrokerMessage
type HandleMessageError = wasmcloud_messaging_0_3_0_types.HandleMessageError

//go:wasmimport [export]wasmcloud:messaging/handler@0.3.0 [stream-new-0]handle-message
func wasm_stream_new_u8() uint64

//go:wasmimport [export]wasmcloud:messaging/handler@0.3.0 [async-lower][stream-read-0]handle-message
func wasm_stream_read_u8(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport [export]wasmcloud:messaging/handler@0.3.0 [async-lower][stream-write-0]handle-message
func wasm_stream_write_u8(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport [export]wasmcloud:messaging/handler@0.3.0 [stream-drop-readable-0]handle-message
func wasm_stream_drop_readable_u8(handle int32)

//go:wasmimport [export]wasmcloud:messaging/handler@0.3.0 [stream-drop-writable-0]handle-message
func wasm_stream_drop_writable_u8(handle int32)

var wasm_stream_vtable_u8 = witTypes.StreamVtable[uint8]{
	Size:         1,
	Align:        1,
	Read:         wasm_stream_read_u8,
	Write:        wasm_stream_write_u8,
	CancelRead:   nil,
	CancelWrite:  nil,
	DropReadable: wasm_stream_drop_readable_u8,
	DropWritable: wasm_stream_drop_writable_u8,
	Lift:         nil,
	Lower:        nil,
}

func MakeStreamU8() (*witTypes.StreamWriter[uint8], *witTypes.StreamReader[uint8]) {
	pair := wasm_stream_new_u8()
	return witTypes.MakeStreamWriter[uint8](&wasm_stream_vtable_u8, int32(pair>>32)),
		witTypes.MakeStreamReader[uint8](&wasm_stream_vtable_u8, int32(pair&0xFFFFFFFF))
}

func LiftStreamU8(handle int32) *witTypes.StreamReader[uint8] {
	return witTypes.MakeStreamReader[uint8](&wasm_stream_vtable_u8, handle)
}
