// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.0.0
//     wasmcloud:keyvalue@0.1.0
//     wasmcloud:messaging@0.2.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:nats@0.2.0
//     wasmcloud:component-go@0.2.0

package wit_exports

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"go.wasmcloud.dev/component/exports/wasmcloud_component_go_wasmcloud_nats_kv_handler_0_2_0/export_wasmcloud_nats_0_1_0_kv_handler"
	"go.wasmcloud.dev/component/imports/wasmcloud_nats_0_1_0_kv"
	"runtime"
	"unsafe"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, (3 * 4), 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport wasmcloud:nats/kv-handler@0.1.0#handle-event
func wasm_export_wasmcloud_nats_0_1_0_kv_handler_handle_event(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr, arg5 uint32, arg6 int64, arg7 int64, arg8 int32) uintptr {

	pinner := &syncExportPinner
	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	value0 := unsafe.String((*uint8)(unsafe.Pointer(arg2)), arg3)
	value1 := unsafe.Slice((*uint8)(unsafe.Pointer(arg4)), arg5)
	witRuntime.Unpin()
	result := export_wasmcloud_nats_0_1_0_kv_handler.HandleEvent(value, wasmcloud_nats_0_1_0_kv.Entry{value0, value1, uint64(arg6), uint64(arg7), uint8(arg8)})

	switch result.Tag() {
	case witTypes.ResultOk:

		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case witTypes.ResultErr:
		payload := result.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_wasmcloud:nats/kv-handler@0.1.0#handle-event
func wasm_export_post_return_wasmcloud_nats_0_1_0_kv_handler_handle_event(result uintptr) {
	syncExportPinner.Unpin()
}
