package wasmcloud:http-keyvalue-crud;

world component {
  include wasmcloud:component-go/imports@0.1.0;
  import wasi:logging/logging@0.1.0-draft;
  import wasi:keyvalue/store@0.2.0-draft; 
  export wasi:http/incoming-handler@0.2.0;
}
