// Generated by `wit-bindgen` 0.61.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.1.0
//     wasmcloud:keyvalue@0.2.0
//     wasmcloud:messaging@0.3.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_secrets_2_1_0_secret

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"go.wasmcloud.dev/component/imports/wasmcloud_secrets_2_1_0_store"
	"runtime"
	"unsafe"
)

type Secret = wasmcloud_secrets_2_1_0_store.Secret

//go:wasmimport wasmcloud:secrets/secret@2.1.0 [async-lower]get
func wasm_import_get(arg0 uintptr) int32

func Get() *wasmcloud_secrets_2_1_0_store.Secret {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 4, 4))

	witAsync.SubtaskWait(uint32(wasm_import_get(returnArea)))

	return wasmcloud_secrets_2_1_0_store.SecretFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 0)))))

}
