// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:component-go@0.2.0
//     componentize-go:union

package wasi_sockets_0_2_8_network

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"go.wasmcloud.dev/component/imports/wasi_io_0_2_8_error"
	"runtime"
	"unsafe"
)

type Error = wasi_io_0_2_8_error.Error

//go:wasmimport wasi:sockets/network@0.2.8 [resource-drop]network
func resourceDropNetwork(handle int32)

type Network struct {
	handle *witRuntime.Handle
}

func (self *Network) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Network) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Network) Handle() int32 {
	return self.handle.Use()
}

func (self *Network) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropNetwork(handle)
	}
}

func NetworkFromOwnHandle(handleValue int32) *Network {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Network{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropNetwork(handleValue)
		}
	}, 0)
	return value
}

func NetworkFromBorrowHandle(handleValue int32) *Network {
	handle := witRuntime.MakeHandle(handleValue)
	return &Network{handle}
}

const (
	ErrorCodeUnknown                  uint8 = 0
	ErrorCodeAccessDenied             uint8 = 1
	ErrorCodeNotSupported             uint8 = 2
	ErrorCodeInvalidArgument          uint8 = 3
	ErrorCodeOutOfMemory              uint8 = 4
	ErrorCodeTimeout                  uint8 = 5
	ErrorCodeConcurrencyConflict      uint8 = 6
	ErrorCodeNotInProgress            uint8 = 7
	ErrorCodeWouldBlock               uint8 = 8
	ErrorCodeInvalidState             uint8 = 9
	ErrorCodeNewSocketLimit           uint8 = 10
	ErrorCodeAddressNotBindable       uint8 = 11
	ErrorCodeAddressInUse             uint8 = 12
	ErrorCodeRemoteUnreachable        uint8 = 13
	ErrorCodeConnectionRefused        uint8 = 14
	ErrorCodeConnectionReset          uint8 = 15
	ErrorCodeConnectionAborted        uint8 = 16
	ErrorCodeDatagramTooLarge         uint8 = 17
	ErrorCodeNameUnresolvable         uint8 = 18
	ErrorCodeTemporaryResolverFailure uint8 = 19
	ErrorCodePermanentResolverFailure uint8 = 20
)

type ErrorCode = uint8

const (
	IpAddressFamilyIpv4 uint8 = 0
	IpAddressFamilyIpv6 uint8 = 1
)

type IpAddressFamily = uint8
type Ipv4Address = witTypes.Tuple4[uint8, uint8, uint8, uint8]
type Ipv6Address = witTypes.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]

const (
	IpAddressIpv4 uint8 = 0
	IpAddressIpv6 uint8 = 1
)

type IpAddress struct {
	tag   uint8
	value any
}

func (self IpAddress) Tag() uint8 {
	return self.tag
}

func (self IpAddress) Ipv4() witTypes.Tuple4[uint8, uint8, uint8, uint8] {
	if self.tag != IpAddressIpv4 {
		panic("tag mismatch")
	}
	return self.value.(witTypes.Tuple4[uint8, uint8, uint8, uint8])
}
func (self IpAddress) Ipv6() witTypes.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16] {
	if self.tag != IpAddressIpv6 {
		panic("tag mismatch")
	}
	return self.value.(witTypes.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16])
}

func MakeIpAddressIpv4(value witTypes.Tuple4[uint8, uint8, uint8, uint8]) IpAddress {
	return IpAddress{IpAddressIpv4, value}
}
func MakeIpAddressIpv6(value witTypes.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]) IpAddress {
	return IpAddress{IpAddressIpv6, value}
}

type Ipv4SocketAddress struct {
	Port    uint16
	Address witTypes.Tuple4[uint8, uint8, uint8, uint8]
}

type Ipv6SocketAddress struct {
	Port     uint16
	FlowInfo uint32
	Address  witTypes.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]
	ScopeId  uint32
}

const (
	IpSocketAddressIpv4 uint8 = 0
	IpSocketAddressIpv6 uint8 = 1
)

type IpSocketAddress struct {
	tag   uint8
	value any
}

func (self IpSocketAddress) Tag() uint8 {
	return self.tag
}

func (self IpSocketAddress) Ipv4() Ipv4SocketAddress {
	if self.tag != IpSocketAddressIpv4 {
		panic("tag mismatch")
	}
	return self.value.(Ipv4SocketAddress)
}
func (self IpSocketAddress) Ipv6() Ipv6SocketAddress {
	if self.tag != IpSocketAddressIpv6 {
		panic("tag mismatch")
	}
	return self.value.(Ipv6SocketAddress)
}

func MakeIpSocketAddressIpv4(value Ipv4SocketAddress) IpSocketAddress {
	return IpSocketAddress{IpSocketAddressIpv4, value}
}
func MakeIpSocketAddressIpv6(value Ipv6SocketAddress) IpSocketAddress {
	return IpSocketAddress{IpSocketAddressIpv6, value}
}

//go:wasmimport wasi:sockets/network@0.2.8 network-error-code
func wasm_import_network_error_code(arg0 int32, arg1 uintptr)

func NetworkErrorCode(err *wasi_io_0_2_8_error.Error) witTypes.Option[ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	wasm_import_network_error_code((err).Handle(), returnArea)
	var option witTypes.Option[ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[ErrorCode]()
	case 1:

		option = witTypes.Some[ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result := option
	return result

}
