// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.0.0
//     wasmcloud:keyvalue@0.1.0
//     wasmcloud:messaging@0.2.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_nats_0_1_0_types

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

// A single header key-value pair.
type HeaderEntry struct {
	Name  string
	Value string
}

// A NATS message. Applies to both core and JetStream messages.
type NatsMessage struct {
	Subject string
	Body    []uint8
	ReplyTo witTypes.Option[string]
	Headers witTypes.Option[[]HeaderEntry]
}

const (
	// Connection / transport error talking to NATS.
	NatsErrorConnection uint8 = 0
	// Request timed out.
	NatsErrorTimeout uint8 = 1
	// No subscriber is listening on the subject. Distinct from `timeout`:
	// retrying immediately will fail the same way until a responder appears.
	NatsErrorNoResponders uint8 = 2
	// The subject is outside the grant this workload was bound with. The
	// string is the subject that was refused.
	NatsErrorSubjectDenied uint8 = 3
	// The payload exceeds the server's advertised `max_payload`. The value
	// is that limit, in bytes.
	NatsErrorMaxPayloadExceeded uint8 = 4
	// JetStream-specific error with a detail string.
	NatsErrorJetstream uint8 = 5
	// The key was not found in a KV bucket.
	NatsErrorKeyNotFound uint8 = 6
	// CAS `update` failed. Payload carries the actual current revision, so a
	// retry does not need a re-read.
	NatsErrorRevisionMismatch uint8 = 7
	// A pull-consumer `fetch` returned empty within the timeout.
	NatsErrorNoMessages uint8 = 8
	// Named resource (stream, bucket, consumer) doesn't exist.
	NatsErrorNotFound uint8 = 9
	// The connected server is too old for this operation. The string names
	// the minimum version required.
	NatsErrorUnsupportedByServer uint8 = 10
	// The connection is down. Distinct from `connection`, which is a
	// transport error on a live connection.
	NatsErrorDisconnected uint8 = 11
	// Anything that doesn't fit the cases above.
	NatsErrorUnexpected uint8 = 12
)

// Typed errors for NATS operations.
type NatsError struct {
	tag   uint8
	value any
}

func (self NatsError) Tag() uint8 {
	return self.tag
}

func (self NatsError) Connection() string {
	if self.tag != NatsErrorConnection {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self NatsError) Timeout() string {
	if self.tag != NatsErrorTimeout {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self NatsError) SubjectDenied() string {
	if self.tag != NatsErrorSubjectDenied {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self NatsError) MaxPayloadExceeded() uint64 {
	if self.tag != NatsErrorMaxPayloadExceeded {
		panic("tag mismatch")
	}
	return self.value.(uint64)
}
func (self NatsError) Jetstream() string {
	if self.tag != NatsErrorJetstream {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self NatsError) RevisionMismatch() uint64 {
	if self.tag != NatsErrorRevisionMismatch {
		panic("tag mismatch")
	}
	return self.value.(uint64)
}
func (self NatsError) NotFound() string {
	if self.tag != NatsErrorNotFound {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self NatsError) UnsupportedByServer() string {
	if self.tag != NatsErrorUnsupportedByServer {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self NatsError) Unexpected() string {
	if self.tag != NatsErrorUnexpected {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeNatsErrorConnection(value string) NatsError {
	return NatsError{NatsErrorConnection, value}
}
func MakeNatsErrorTimeout(value string) NatsError {
	return NatsError{NatsErrorTimeout, value}
}
func MakeNatsErrorNoResponders() NatsError {
	return NatsError{NatsErrorNoResponders, nil}
}
func MakeNatsErrorSubjectDenied(value string) NatsError {
	return NatsError{NatsErrorSubjectDenied, value}
}
func MakeNatsErrorMaxPayloadExceeded(value uint64) NatsError {
	return NatsError{NatsErrorMaxPayloadExceeded, value}
}
func MakeNatsErrorJetstream(value string) NatsError {
	return NatsError{NatsErrorJetstream, value}
}
func MakeNatsErrorKeyNotFound() NatsError {
	return NatsError{NatsErrorKeyNotFound, nil}
}
func MakeNatsErrorRevisionMismatch(value uint64) NatsError {
	return NatsError{NatsErrorRevisionMismatch, value}
}
func MakeNatsErrorNoMessages() NatsError {
	return NatsError{NatsErrorNoMessages, nil}
}
func MakeNatsErrorNotFound(value string) NatsError {
	return NatsError{NatsErrorNotFound, value}
}
func MakeNatsErrorUnsupportedByServer(value string) NatsError {
	return NatsError{NatsErrorUnsupportedByServer, value}
}
func MakeNatsErrorDisconnected() NatsError {
	return NatsError{NatsErrorDisconnected, nil}
}
func MakeNatsErrorUnexpected(value string) NatsError {
	return NatsError{NatsErrorUnexpected, value}
}
