// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.0.0
//     wasmcloud:keyvalue@0.1.0
//     wasmcloud:messaging@0.2.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_nats_0_1_0_types

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

// A single header key-value pair.
//
// Names must be printable ASCII without `:`; values may not contain CR or
// LF. Anything else is refused with `invalid-header` rather than reaching
// the wire.
type HeaderEntry struct {
	Name  string
	Value string
}

// A NATS message. Applies to both core and JetStream messages.
type NatsMessage struct {
	Subject string
	Body    []uint8
	ReplyTo witTypes.Option[string]
	Headers witTypes.Option[[]HeaderEntry]
}

const (
	// The name is in a space the host reserves for itself — the JetStream
	// API, the KV/object-store key spaces, `$SYS`, or the host's own lattice.
	DenialReasonReserved uint8 = 0
	// No grant on this binding covers the name.
	DenialReasonNotGranted uint8 = 1
	// A publish or request subject contained `*` or `>`.
	DenialReasonWildcardNotAllowed uint8 = 2
)

// Why the host refused a name.
type DenialReason = uint8

const (
	// A publish or request subject.
	DeniedResourceSubject uint8 = 0
	// A JetStream stream name.
	DeniedResourceStream uint8 = 1
	// A KV bucket name.
	DeniedResourceBucket uint8 = 2
	// A stored JetStream message, named `<stream>#<sequence>`.
	//
	// A read of a stored message is checked against the subject grant, but
	// the refusal names the sequence rather than the subject it was stored
	// on: naming the subject would let a caller walk sequences to enumerate
	// subjects it was never granted. Widen `subject-allow` to cover the
	// subject the stream stores those messages on.
	DeniedResourceMessage uint8 = 3
)

// What kind of name was refused, and so which grant the binding would need:
// `subject-allow`, `stream-allow`, or `bucket-allow`. Those are declared by
// whoever configured the host, not by the workload, so a refusal here is
// something to take to an operator.
//
// Subscription patterns are not here: they are checked once at bind time,
// where a refusal fails the deployment rather than reaching a guest.
type DeniedResource = uint8

// A refusal by the host's grant check.
type Denial struct {
	Reason DenialReason
	Target DeniedResource
	// The name that was refused.
	Name string
}

const (
	// Connection / transport error talking to NATS.
	NatsErrorConnection uint8 = 0
	// Request timed out.
	NatsErrorTimeout uint8 = 1
	// No subscriber is listening on the subject. Distinct from `timeout`:
	// retrying immediately will fail the same way until a responder appears.
	NatsErrorNoResponders uint8 = 2
	// The name is outside the grant this workload was bound with, or in a
	// space the host reserves. Replaces `@0.1.0`'s `subject-denied(string)`.
	NatsErrorDenied uint8 = 3
	// The payload exceeds the server's advertised `max_payload`. The value
	// is that limit, in bytes. Header bytes count toward it.
	NatsErrorMaxPayloadExceeded uint8 = 4
	// A header name or value is not representable on the NATS wire.
	NatsErrorInvalidHeader uint8 = 5
	// JetStream-specific error with a detail string.
	NatsErrorJetstream uint8 = 6
	// The key was not found in a KV bucket.
	NatsErrorKeyNotFound uint8 = 7
	// CAS `update` failed. Payload carries the actual current revision, so a
	// retry does not need a re-read.
	NatsErrorRevisionMismatch uint8 = 8
	// A pull-consumer `fetch` returned empty within the timeout: the
	// consumer had nothing to give. Compare `limit-exceeded`, where the
	// request never ran.
	NatsErrorNoMessages uint8 = 9
	// The server refused the request outright because it exceeds a limit the
	// consumer was provisioned with — a batch over `max-request-batch`, a
	// byte bound over `max-request-max-bytes`, or too many waiting pulls.
	// Nothing was delivered, and retrying unchanged fails the same way;
	// `info` reports the limits to size the next request against.
	NatsErrorLimitExceeded uint8 = 10
	// Named resource (stream, bucket, consumer) doesn't exist.
	NatsErrorNotFound uint8 = 11
	// The connected server is too old for this operation. The string names
	// the minimum version required.
	NatsErrorUnsupportedByServer uint8 = 12
	// No live connection is bound to this workload. Distinct from
	// `connection`, which is a transport error on a live connection.
	NatsErrorDisconnected uint8 = 13
	// Anything that doesn't fit the cases above.
	NatsErrorUnexpected uint8 = 14
)

// Typed errors for NATS operations.
type NatsError struct {
	tag   uint8
	value any
}

func (self NatsError) Tag() uint8 {
	return self.tag
}

func (self NatsError) Connection() string {
	if self.tag != NatsErrorConnection {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self NatsError) Timeout() string {
	if self.tag != NatsErrorTimeout {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self NatsError) Denied() Denial {
	if self.tag != NatsErrorDenied {
		panic("tag mismatch")
	}
	return self.value.(Denial)
}
func (self NatsError) MaxPayloadExceeded() uint64 {
	if self.tag != NatsErrorMaxPayloadExceeded {
		panic("tag mismatch")
	}
	return self.value.(uint64)
}
func (self NatsError) InvalidHeader() string {
	if self.tag != NatsErrorInvalidHeader {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self NatsError) Jetstream() string {
	if self.tag != NatsErrorJetstream {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self NatsError) RevisionMismatch() uint64 {
	if self.tag != NatsErrorRevisionMismatch {
		panic("tag mismatch")
	}
	return self.value.(uint64)
}
func (self NatsError) LimitExceeded() string {
	if self.tag != NatsErrorLimitExceeded {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self NatsError) NotFound() string {
	if self.tag != NatsErrorNotFound {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self NatsError) UnsupportedByServer() string {
	if self.tag != NatsErrorUnsupportedByServer {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self NatsError) Unexpected() string {
	if self.tag != NatsErrorUnexpected {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeNatsErrorConnection(value string) NatsError {
	return NatsError{NatsErrorConnection, value}
}
func MakeNatsErrorTimeout(value string) NatsError {
	return NatsError{NatsErrorTimeout, value}
}
func MakeNatsErrorNoResponders() NatsError {
	return NatsError{NatsErrorNoResponders, nil}
}
func MakeNatsErrorDenied(value Denial) NatsError {
	return NatsError{NatsErrorDenied, value}
}
func MakeNatsErrorMaxPayloadExceeded(value uint64) NatsError {
	return NatsError{NatsErrorMaxPayloadExceeded, value}
}
func MakeNatsErrorInvalidHeader(value string) NatsError {
	return NatsError{NatsErrorInvalidHeader, value}
}
func MakeNatsErrorJetstream(value string) NatsError {
	return NatsError{NatsErrorJetstream, value}
}
func MakeNatsErrorKeyNotFound() NatsError {
	return NatsError{NatsErrorKeyNotFound, nil}
}
func MakeNatsErrorRevisionMismatch(value uint64) NatsError {
	return NatsError{NatsErrorRevisionMismatch, value}
}
func MakeNatsErrorNoMessages() NatsError {
	return NatsError{NatsErrorNoMessages, nil}
}
func MakeNatsErrorLimitExceeded(value string) NatsError {
	return NatsError{NatsErrorLimitExceeded, value}
}
func MakeNatsErrorNotFound(value string) NatsError {
	return NatsError{NatsErrorNotFound, value}
}
func MakeNatsErrorUnsupportedByServer(value string) NatsError {
	return NatsError{NatsErrorUnsupportedByServer, value}
}
func MakeNatsErrorDisconnected() NatsError {
	return NatsError{NatsErrorDisconnected, nil}
}
func MakeNatsErrorUnexpected(value string) NatsError {
	return NatsError{NatsErrorUnexpected, value}
}
