// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.0.0
//     wasmcloud:keyvalue@0.1.0
//     wasmcloud:messaging@0.2.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_nats_0_1_0_kv

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"go.wasmcloud.dev/component/imports/wasmcloud_nats_0_1_0_types"
	"runtime"
	"unsafe"
)

type NatsError = wasmcloud_nats_0_1_0_types.NatsError

const (
	KvOperationPut    uint8 = 0
	KvOperationDelete uint8 = 1
	KvOperationPurge  uint8 = 2
)

// Operation that produced a KV entry.
type KvOperation = uint8

// A single entry as seen in get/history/watch.
type Entry struct {
	Key                string
	Value              []uint8
	Revision           uint64
	CreatedAtUnixNanos uint64
	Operation          KvOperation
}

// Status snapshot for a bucket.
type BucketStatus struct {
	Bucket     string
	Values     uint64
	History    uint8
	TtlSeconds uint64
	Bytes      uint64
}

//go:wasmimport wasmcloud:nats/kv@0.1.0 [resource-drop]bucket
func resourceDropBucket(handle int32)

// Handle to an open KV bucket.
type Bucket struct {
	handle *witRuntime.Handle
}

func (self *Bucket) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Bucket) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Bucket) Handle() int32 {
	return self.handle.Use()
}

func (self *Bucket) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropBucket(handle)
	}
}

func BucketFromOwnHandle(handleValue int32) *Bucket {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Bucket{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropBucket(handleValue)
		}
	}, 0)
	return value
}

func BucketFromBorrowHandle(handleValue int32) *Bucket {
	handle := witRuntime.MakeHandle(handleValue)
	return &Bucket{handle}
}

//go:wasmimport wasmcloud:nats/kv@0.1.0 [method]bucket.get
func wasm_import_method_bucket_get(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Bucket) Get(key string) witTypes.Result[witTypes.Option[Entry], wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (40 + 4*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	wasm_import_method_bucket_get((self).Handle(), uintptr(utf8), uint32(len(key)), returnArea)
	var result witTypes.Result[witTypes.Option[Entry], wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		var option witTypes.Option[Entry]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			option = witTypes.None[Entry]()
		case 1:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))
			value0 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 3*4))))

			option = witTypes.Some[Entry](Entry{value, value0, uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 4*4)))), uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 4*4)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (32 + 4*4)))))})
		default:
			panic("unreachable")
		}

		result = witTypes.Ok[witTypes.Option[Entry], wasmcloud_nats_0_1_0_types.NatsError](option)
	case 1:
		var variant wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value1)

		case 1:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value2)

		case 2:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorSubjectDenied(value3)

		case 4:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value4)

		case 6:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 7:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 8:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 9:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value5)

		case 10:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value6)

		case 11:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 12:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value7)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Option[Entry], wasmcloud_nats_0_1_0_types.NatsError](variant)
	default:
		panic("unreachable")
	}
	result8 := result
	return result8

}

//go:wasmimport wasmcloud:nats/kv@0.1.0 [method]bucket.put
func wasm_import_method_bucket_put(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func (self *Bucket) Put(key string, value []uint8) witTypes.Result[uint64, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	data := unsafe.Pointer(unsafe.SliceData(value))
	pinner.Pin(data)
	wasm_import_method_bucket_put((self).Handle(), uintptr(utf8), uint32(len(key)), uintptr(data), uint32(len(value)), returnArea)
	var result witTypes.Result[uint64, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[uint64, wasmcloud_nats_0_1_0_types.NatsError](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
	case 1:
		var variant wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value0)

		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value1)

		case 2:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorSubjectDenied(value2)

		case 4:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value3)

		case 6:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 7:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 8:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 9:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value4)

		case 10:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value5)

		case 11:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 12:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value6)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[uint64, wasmcloud_nats_0_1_0_types.NatsError](variant)
	default:
		panic("unreachable")
	}
	result7 := result
	return result7

}

//go:wasmimport wasmcloud:nats/kv@0.1.0 [method]bucket.create
func wasm_import_method_bucket_create(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func (self *Bucket) Create(key string, value []uint8) witTypes.Result[uint64, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	data := unsafe.Pointer(unsafe.SliceData(value))
	pinner.Pin(data)
	wasm_import_method_bucket_create((self).Handle(), uintptr(utf8), uint32(len(key)), uintptr(data), uint32(len(value)), returnArea)
	var result witTypes.Result[uint64, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[uint64, wasmcloud_nats_0_1_0_types.NatsError](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
	case 1:
		var variant wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value0)

		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value1)

		case 2:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorSubjectDenied(value2)

		case 4:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value3)

		case 6:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 7:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 8:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 9:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value4)

		case 10:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value5)

		case 11:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 12:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value6)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[uint64, wasmcloud_nats_0_1_0_types.NatsError](variant)
	default:
		panic("unreachable")
	}
	result7 := result
	return result7

}

//go:wasmimport wasmcloud:nats/kv@0.1.0 [method]bucket.update
func wasm_import_method_bucket_update(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 int64, arg6 uintptr)

func (self *Bucket) Update(key string, value []uint8, expectedRevision uint64) witTypes.Result[uint64, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	data := unsafe.Pointer(unsafe.SliceData(value))
	pinner.Pin(data)
	wasm_import_method_bucket_update((self).Handle(), uintptr(utf8), uint32(len(key)), uintptr(data), uint32(len(value)), int64(expectedRevision), returnArea)
	var result witTypes.Result[uint64, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[uint64, wasmcloud_nats_0_1_0_types.NatsError](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
	case 1:
		var variant wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value0)

		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value1)

		case 2:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorSubjectDenied(value2)

		case 4:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value3)

		case 6:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 7:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 8:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 9:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value4)

		case 10:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value5)

		case 11:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 12:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value6)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[uint64, wasmcloud_nats_0_1_0_types.NatsError](variant)
	default:
		panic("unreachable")
	}
	result7 := result
	return result7

}

//go:wasmimport wasmcloud:nats/kv@0.1.0 [method]bucket.delete
func wasm_import_method_bucket_delete(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Bucket) Delete(key string) witTypes.Result[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	wasm_import_method_bucket_delete((self).Handle(), uintptr(utf8), uint32(len(key)), returnArea)
	var result witTypes.Result[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError](witTypes.Unit{})
	case 1:
		var variant wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value0)

		case 2:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorSubjectDenied(value1)

		case 4:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value2)

		case 6:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 7:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 8:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 9:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value3)

		case 10:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value4)

		case 11:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 12:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value5)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError](variant)
	default:
		panic("unreachable")
	}
	result6 := result
	return result6

}

//go:wasmimport wasmcloud:nats/kv@0.1.0 [method]bucket.purge
func wasm_import_method_bucket_purge(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Bucket) Purge(key string) witTypes.Result[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	wasm_import_method_bucket_purge((self).Handle(), uintptr(utf8), uint32(len(key)), returnArea)
	var result witTypes.Result[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError](witTypes.Unit{})
	case 1:
		var variant wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value0)

		case 2:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorSubjectDenied(value1)

		case 4:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value2)

		case 6:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 7:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 8:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 9:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value3)

		case 10:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value4)

		case 11:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 12:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value5)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, wasmcloud_nats_0_1_0_types.NatsError](variant)
	default:
		panic("unreachable")
	}
	result6 := result
	return result6

}

//go:wasmimport wasmcloud:nats/kv@0.1.0 [method]bucket.keys
func wasm_import_method_bucket_keys(arg0 int32, arg1 uintptr)

func (self *Bucket) Keys() witTypes.Result[[]string, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	wasm_import_method_bucket_keys((self).Handle(), returnArea)
	var result7 witTypes.Result[[]string, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), index*(2*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, value)
		}

		result7 = witTypes.Ok[[]string, wasmcloud_nats_0_1_0_types.NatsError](result)
	case 1:
		var variant wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value0)

		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value1)

		case 2:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorSubjectDenied(value2)

		case 4:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value3)

		case 6:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 7:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 8:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 9:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value4)

		case 10:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value5)

		case 11:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 12:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value6)

		default:
			panic("unreachable")
		}

		result7 = witTypes.Err[[]string, wasmcloud_nats_0_1_0_types.NatsError](variant)
	default:
		panic("unreachable")
	}
	result8 := result7
	return result8

}

//go:wasmimport wasmcloud:nats/kv@0.1.0 [method]bucket.history
func wasm_import_method_bucket_history(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Bucket) History(key string) witTypes.Result[[]Entry, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	wasm_import_method_bucket_history((self).Handle(), uintptr(utf8), uint32(len(key)), returnArea)
	var result8 witTypes.Result[[]Entry, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result := make([]Entry, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), index*(24+4*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
			value0 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

			result = append(result, Entry{value, value0, uint64(*(*int64)(unsafe.Add(unsafe.Pointer(base), (4 * 4)))), uint64(*(*int64)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 4*4)))))})
		}

		result8 = witTypes.Ok[[]Entry, wasmcloud_nats_0_1_0_types.NatsError](result)
	case 1:
		var variant wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value1)

		case 1:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value2)

		case 2:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorSubjectDenied(value3)

		case 4:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value4)

		case 6:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 7:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 8:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 9:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value5)

		case 10:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value6)

		case 11:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 12:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value7)

		default:
			panic("unreachable")
		}

		result8 = witTypes.Err[[]Entry, wasmcloud_nats_0_1_0_types.NatsError](variant)
	default:
		panic("unreachable")
	}
	result9 := result8
	return result9

}

//go:wasmimport wasmcloud:nats/kv@0.1.0 [method]bucket.status
func wasm_import_method_bucket_status(arg0 int32, arg1 uintptr)

func (self *Bucket) Status() witTypes.Result[BucketStatus, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (40 + 2*4), 8))
	wasm_import_method_bucket_status((self).Handle(), returnArea)
	var result witTypes.Result[BucketStatus, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))

		result = witTypes.Ok[BucketStatus, wasmcloud_nats_0_1_0_types.NatsError](BucketStatus{value, uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 2*4))))), uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 2*4)))), uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (32 + 2*4))))})
	case 1:
		var variant wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value0)

		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value1)

		case 2:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorSubjectDenied(value2)

		case 4:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value3)

		case 6:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 7:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 8:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 9:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value4)

		case 10:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value5)

		case 11:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 12:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value6)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[BucketStatus, wasmcloud_nats_0_1_0_types.NatsError](variant)
	default:
		panic("unreachable")
	}
	result7 := result
	return result7

}

//go:wasmimport wasmcloud:nats/kv@0.1.0 open
func wasm_import_open(arg0 uintptr, arg1 uint32, arg2 uintptr)

func Open(bucket string) witTypes.Result[*Bucket, wasmcloud_nats_0_1_0_types.NatsError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(bucket))
	pinner.Pin(utf8)
	wasm_import_open(uintptr(utf8), uint32(len(bucket)), returnArea)
	var result witTypes.Result[*Bucket, wasmcloud_nats_0_1_0_types.NatsError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*Bucket, wasmcloud_nats_0_1_0_types.NatsError](BucketFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))))
	case 1:
		var variant wasmcloud_nats_0_1_0_types.NatsError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorConnection(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorTimeout(value0)

		case 2:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoResponders()

		case 3:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorSubjectDenied(value1)

		case 4:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorMaxPayloadExceeded(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 5:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorJetstream(value2)

		case 6:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorKeyNotFound()

		case 7:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorRevisionMismatch(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 8:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNoMessages()

		case 9:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorNotFound(value3)

		case 10:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnsupportedByServer(value4)

		case 11:

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorDisconnected()

		case 12:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = wasmcloud_nats_0_1_0_types.MakeNatsErrorUnexpected(value5)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*Bucket, wasmcloud_nats_0_1_0_types.NatsError](variant)
	default:
		panic("unreachable")
	}
	result6 := result
	return result6

}
