// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.0.0
//     wasmcloud:keyvalue@0.1.0
//     wasmcloud:messaging@0.2.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_keyvalue_0_1_0_atomics

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"go.wasmcloud.dev/component/imports/wasmcloud_keyvalue_0_1_0_types"
	"runtime"
	"unsafe"
)

type Bucket = wasmcloud_keyvalue_0_1_0_types.Bucket
type Error = wasmcloud_keyvalue_0_1_0_types.Error

//go:wasmimport wasmcloud:keyvalue/atomics@0.1.0 [async-lower]increment
func wasm_import_increment(arg0 int32, arg1 uintptr, arg2 uint32, arg3 int64, arg4 uintptr) int32

func Increment(bucket *wasmcloud_keyvalue_0_1_0_types.Bucket, key string, delta int64) witTypes.Result[int64, wasmcloud_keyvalue_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_increment((bucket).Handle(), uintptr(utf8), uint32(len(key)), delta, returnArea)))
	var result witTypes.Result[int64, wasmcloud_keyvalue_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[int64, wasmcloud_keyvalue_0_1_0_types.Error](*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8)))
	case 1:
		var variant wasmcloud_keyvalue_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = wasmcloud_keyvalue_0_1_0_types.MakeErrorNoSuchStore()

		case 1:

			variant = wasmcloud_keyvalue_0_1_0_types.MakeErrorAccessDenied()

		case 2:

			variant = wasmcloud_keyvalue_0_1_0_types.MakeErrorInvalidArgument()

		case 3:

			variant = wasmcloud_keyvalue_0_1_0_types.MakeErrorPreconditionFailed()

		case 4:

			variant = wasmcloud_keyvalue_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_keyvalue_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_keyvalue_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = wasmcloud_keyvalue_0_1_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[int64, wasmcloud_keyvalue_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}
