// Generated by `wit-bindgen` 0.61.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasmcloud:host@0.1.3
//     wasmcloud:plugin-go@0.1.0
//     componentize-go:union

package wasmcloud_host_0_1_3_cancel

import ()

// An opaque, host-minted identifier for one in-flight invocation.
type JobId = uint64

//go:wasmimport wasmcloud:host/cancel@0.1.3 current-job
func wasm_import_current_job() int64

func CurrentJob() uint64 {

	result := wasm_import_current_job()
	return uint64(result)

}

//go:wasmimport wasmcloud:host/cancel@0.1.3 request-cancel
func wasm_import_request_cancel(arg0 int64) int32

func RequestCancel(job uint64) bool {

	result := wasm_import_request_cancel(int64(job))
	return (result != 0)

}

//go:wasmimport wasmcloud:host/cancel@0.1.3 is-cancelled
func wasm_import_is_cancelled() int32

func IsCancelled() bool {

	result := wasm_import_is_cancelled()
	return (result != 0)

}
