// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:component-go@0.2.0
//     componentize-go:union

package wasi_clocks_0_3_0_system_clock

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"runtime"
	"unsafe"
)

type Duration = uint64

type Instant struct {
	Seconds     int64
	Nanoseconds uint32
}

//go:wasmimport wasi:clocks/system-clock@0.3.0 now
func wasm_import_now(arg0 uintptr)

func Now() Instant {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 16, 8))
	wasm_import_now(returnArea)
	result := Instant{*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 0)), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))}
	return result

}

//go:wasmimport wasi:clocks/system-clock@0.3.0 get-resolution
func wasm_import_get_resolution() int64

func GetResolution() uint64 {

	result := wasm_import_get_resolution()
	return uint64(result)

}
