// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.0.0
//     wasmcloud:keyvalue@0.1.0
//     wasmcloud:messaging@0.2.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:nats@0.2.0
//     wasmcloud:component-go@0.2.0

package wit_exports

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"go.wasmcloud.dev/component/exports/wasmcloud_component_go_wasmcloud_nats_async_kv_handler_0_2_0/export_wasmcloud_nats_0_2_0_kv_handler"
	"go.wasmcloud.dev/component/imports/wasmcloud_nats_0_2_0_kv"
	"runtime"
	"unsafe"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, 0, 1))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport [async-lift]wasmcloud:nats/kv-handler@0.2.0#handle-event
func wasm_export_wasmcloud_nats_0_2_0_kv_handler_handle_event(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr, arg5 uint32, arg6 int64, arg7 int64, arg8 int32) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
		value0 := unsafe.String((*uint8)(unsafe.Pointer(arg2)), arg3)
		value1 := unsafe.Slice((*uint8)(unsafe.Pointer(arg4)), arg5)
		witRuntime.Unpin()
		result := export_wasmcloud_nats_0_2_0_kv_handler.HandleEvent(value, wasmcloud_nats_0_2_0_kv.Entry{value0, value1, uint64(arg6), uint64(arg7), uint8(arg8)})
		var option int32
		var option2 uintptr
		var option3 uint32
		switch result.Tag() {
		case witTypes.ResultOk:

			option = int32(0)
			option2 = 0
			option3 = 0
		case witTypes.ResultErr:
			payload := result.Err()
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)

			option = int32(1)
			option2 = uintptr(utf8)
			option3 = uint32(len(payload))
		default:
			panic("unreachable")
		}
		wasm_export_task_return_wasmcloud_nats_0_2_0_kv_handler_handle_event(option, option2, option3)

	}))
}

//go:wasmexport [callback][async-lift]wasmcloud:nats/kv-handler@0.2.0#handle-event
func wasm_export_callback_wasmcloud_nats_0_2_0_kv_handler_handle_event(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wasmcloud:nats/kv-handler@0.2.0 [task-return]handle-event
func wasm_export_task_return_wasmcloud_nats_0_2_0_kv_handler_handle_event(arg0 int32, arg1 uintptr, arg2 uint32)
