// Generated by `wit-bindgen` 0.61.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.1.0
//     wasmcloud:keyvalue@0.2.0
//     wasmcloud:messaging@0.3.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_blobstore_0_1_0_blobstore

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"go.wasmcloud.dev/component/imports/wasmcloud_blobstore_0_1_0_container"
	"go.wasmcloud.dev/component/imports/wasmcloud_blobstore_0_1_0_types"
	"runtime"
	"unsafe"
)

type Container = wasmcloud_blobstore_0_1_0_container.Container
type Error = wasmcloud_blobstore_0_1_0_types.Error
type ContainerName = string
type ObjectId = wasmcloud_blobstore_0_1_0_types.ObjectId

//go:wasmimport wasmcloud:blobstore/blobstore@0.1.0 [async-lower]create-container
func wasm_import_create_container(arg0 uintptr, arg1 uint32, arg2 uintptr) int32

func CreateContainer(name string) witTypes.Result[*wasmcloud_blobstore_0_1_0_container.Container, wasmcloud_blobstore_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(name))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_create_container(uintptr(utf8), uint32(len(name)), returnArea)))
	var result witTypes.Result[*wasmcloud_blobstore_0_1_0_container.Container, wasmcloud_blobstore_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*wasmcloud_blobstore_0_1_0_container.Container, wasmcloud_blobstore_0_1_0_types.Error](wasmcloud_blobstore_0_1_0_container.ContainerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant wasmcloud_blobstore_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchContainer()

		case 1:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorContainerAlreadyExists()

		case 2:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchObject()

		case 3:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorAccessDenied()

		case 4:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*wasmcloud_blobstore_0_1_0_container.Container, wasmcloud_blobstore_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:blobstore/blobstore@0.1.0 [async-lower]get-container
func wasm_import_get_container(arg0 uintptr, arg1 uint32, arg2 uintptr) int32

func GetContainer(name string) witTypes.Result[*wasmcloud_blobstore_0_1_0_container.Container, wasmcloud_blobstore_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(name))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_get_container(uintptr(utf8), uint32(len(name)), returnArea)))
	var result witTypes.Result[*wasmcloud_blobstore_0_1_0_container.Container, wasmcloud_blobstore_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*wasmcloud_blobstore_0_1_0_container.Container, wasmcloud_blobstore_0_1_0_types.Error](wasmcloud_blobstore_0_1_0_container.ContainerFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant wasmcloud_blobstore_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchContainer()

		case 1:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorContainerAlreadyExists()

		case 2:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchObject()

		case 3:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorAccessDenied()

		case 4:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*wasmcloud_blobstore_0_1_0_container.Container, wasmcloud_blobstore_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:blobstore/blobstore@0.1.0 [async-lower]delete-container
func wasm_import_delete_container(arg0 uintptr, arg1 uint32, arg2 uintptr) int32

func DeleteContainer(name string) witTypes.Result[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(name))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_delete_container(uintptr(utf8), uint32(len(name)), returnArea)))
	var result witTypes.Result[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error](witTypes.Unit{})
	case 1:
		var variant wasmcloud_blobstore_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchContainer()

		case 1:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorContainerAlreadyExists()

		case 2:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchObject()

		case 3:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorAccessDenied()

		case 4:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:blobstore/blobstore@0.1.0 [async-lower]container-exists
func wasm_import_container_exists(arg0 uintptr, arg1 uint32, arg2 uintptr) int32

func ContainerExists(name string) witTypes.Result[bool, wasmcloud_blobstore_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(name))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_container_exists(uintptr(utf8), uint32(len(name)), returnArea)))
	var result witTypes.Result[bool, wasmcloud_blobstore_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[bool, wasmcloud_blobstore_0_1_0_types.Error]((uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) != 0))
	case 1:
		var variant wasmcloud_blobstore_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchContainer()

		case 1:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorContainerAlreadyExists()

		case 2:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchObject()

		case 3:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorAccessDenied()

		case 4:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[bool, wasmcloud_blobstore_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:blobstore/blobstore@0.1.0 [async-lower]copy-object
func wasm_import_copy_object(arg0 uintptr, arg1 uintptr) int32

func CopyObject(src wasmcloud_blobstore_0_1_0_types.ObjectId, dest wasmcloud_blobstore_0_1_0_types.ObjectId) witTypes.Result[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	params := witRuntime.Allocate(pinner, (8 * 4), 4)
	utf8 := unsafe.Pointer(unsafe.StringData((src).Container))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 4)) = uint32(uint32(len((src).Container)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 0)) = uint32(uintptr(uintptr(utf8)))
	utf80 := unsafe.Pointer(unsafe.StringData((src).Object))
	pinner.Pin(utf80)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (3 * 4))) = uint32(uint32(len((src).Object)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (2 * 4))) = uint32(uintptr(uintptr(utf80)))
	utf81 := unsafe.Pointer(unsafe.StringData((dest).Container))
	pinner.Pin(utf81)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (4*4))), 4)) = uint32(uint32(len((dest).Container)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (4*4))), 0)) = uint32(uintptr(uintptr(utf81)))
	utf82 := unsafe.Pointer(unsafe.StringData((dest).Object))
	pinner.Pin(utf82)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (4*4))), (3 * 4))) = uint32(uint32(len((dest).Object)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (4*4))), (2 * 4))) = uint32(uintptr(uintptr(utf82)))

	witAsync.SubtaskWait(uint32(wasm_import_copy_object(uintptr(params), returnArea)))
	var result witTypes.Result[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error](witTypes.Unit{})
	case 1:
		var variant wasmcloud_blobstore_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchContainer()

		case 1:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorContainerAlreadyExists()

		case 2:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchObject()

		case 3:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorAccessDenied()

		case 4:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:blobstore/blobstore@0.1.0 [async-lower]move-object
func wasm_import_move_object(arg0 uintptr, arg1 uintptr) int32

func MoveObject(src wasmcloud_blobstore_0_1_0_types.ObjectId, dest wasmcloud_blobstore_0_1_0_types.ObjectId) witTypes.Result[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	params := witRuntime.Allocate(pinner, (8 * 4), 4)
	utf8 := unsafe.Pointer(unsafe.StringData((src).Container))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 4)) = uint32(uint32(len((src).Container)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 0)) = uint32(uintptr(uintptr(utf8)))
	utf80 := unsafe.Pointer(unsafe.StringData((src).Object))
	pinner.Pin(utf80)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (3 * 4))) = uint32(uint32(len((src).Object)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (2 * 4))) = uint32(uintptr(uintptr(utf80)))
	utf81 := unsafe.Pointer(unsafe.StringData((dest).Container))
	pinner.Pin(utf81)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (4*4))), 4)) = uint32(uint32(len((dest).Container)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (4*4))), 0)) = uint32(uintptr(uintptr(utf81)))
	utf82 := unsafe.Pointer(unsafe.StringData((dest).Object))
	pinner.Pin(utf82)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (4*4))), (3 * 4))) = uint32(uint32(len((dest).Object)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (4*4))), (2 * 4))) = uint32(uintptr(uintptr(utf82)))

	witAsync.SubtaskWait(uint32(wasm_import_move_object(uintptr(params), returnArea)))
	var result witTypes.Result[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error](witTypes.Unit{})
	case 1:
		var variant wasmcloud_blobstore_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchContainer()

		case 1:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorContainerAlreadyExists()

		case 2:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchObject()

		case 3:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorAccessDenied()

		case 4:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}
