// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.0.0
//     wasmcloud:keyvalue@0.1.0
//     wasmcloud:messaging@0.2.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_blobstore_0_1_0_container

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"go.wasmcloud.dev/component/imports/wasmcloud_blobstore_0_1_0_types"
	"runtime"
	"unsafe"
)

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [stream-new-0][method]container.get-data
func wasm_stream_new_u8() uint64

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [async-lower][stream-read-0][method]container.get-data
func wasm_stream_read_u8(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [async-lower][stream-write-0][method]container.get-data
func wasm_stream_write_u8(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [stream-drop-readable-0][method]container.get-data
func wasm_stream_drop_readable_u8(handle int32)

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [stream-drop-writable-0][method]container.get-data
func wasm_stream_drop_writable_u8(handle int32)

var wasm_stream_vtable_u8 = witTypes.StreamVtable[uint8]{
	1,
	1,
	wasm_stream_read_u8,
	wasm_stream_write_u8,
	nil,
	nil,
	wasm_stream_drop_readable_u8,
	wasm_stream_drop_writable_u8,
	nil,
	nil,
}

func MakeStreamU8() (*witTypes.StreamWriter[uint8], *witTypes.StreamReader[uint8]) {
	pair := wasm_stream_new_u8()
	return witTypes.MakeStreamWriter[uint8](&wasm_stream_vtable_u8, int32(pair>>32)),
		witTypes.MakeStreamReader[uint8](&wasm_stream_vtable_u8, int32(pair&0xFFFFFFFF))
}

func LiftStreamU8(handle int32) *witTypes.StreamReader[uint8] {
	return witTypes.MakeStreamReader[uint8](&wasm_stream_vtable_u8, handle)
}

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [stream-new-0][method]container.list-objects
func wasm_stream_new_string() uint64

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [async-lower][stream-read-0][method]container.list-objects
func wasm_stream_read_string(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [async-lower][stream-write-0][method]container.list-objects
func wasm_stream_write_string(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [stream-drop-readable-0][method]container.list-objects
func wasm_stream_drop_readable_string(handle int32)

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [stream-drop-writable-0][method]container.list-objects
func wasm_stream_drop_writable_string(handle int32)

func wasm_stream_lift_string(src unsafe.Pointer) string {
	value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(src), 4)))

	return value
}

func wasm_stream_lower_string(
	pinner *runtime.Pinner,
	value string,
	dst unsafe.Pointer,
) func() {
	utf8 := unsafe.Pointer(unsafe.StringData(value))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(dst), 4)) = uint32(uint32(len(value)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(dst), 0)) = uint32(uintptr(uintptr(utf8)))

	return func() {}
}

var wasm_stream_vtable_string = witTypes.StreamVtable[string]{
	(2 * 4),
	4,
	wasm_stream_read_string,
	wasm_stream_write_string,
	nil,
	nil,
	wasm_stream_drop_readable_string,
	wasm_stream_drop_writable_string,
	wasm_stream_lift_string,
	wasm_stream_lower_string,
}

func MakeStreamString() (*witTypes.StreamWriter[string], *witTypes.StreamReader[string]) {
	pair := wasm_stream_new_string()
	return witTypes.MakeStreamWriter[string](&wasm_stream_vtable_string, int32(pair>>32)),
		witTypes.MakeStreamReader[string](&wasm_stream_vtable_string, int32(pair&0xFFFFFFFF))
}

func LiftStreamString(handle int32) *witTypes.StreamReader[string] {
	return witTypes.MakeStreamReader[string](&wasm_stream_vtable_string, handle)
}

type ContainerMetadata = wasmcloud_blobstore_0_1_0_types.ContainerMetadata
type Error = wasmcloud_blobstore_0_1_0_types.Error
type ObjectMetadata = wasmcloud_blobstore_0_1_0_types.ObjectMetadata
type ObjectName = string

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [resource-drop]container
func resourceDropContainer(handle int32)

// this defines the `container` resource
type Container struct {
	handle *witRuntime.Handle
}

func (self *Container) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Container) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Container) Handle() int32 {
	return self.handle.Use()
}

func (self *Container) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropContainer(handle)
	}
}

func ContainerFromOwnHandle(handleValue int32) *Container {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Container{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropContainer(handleValue)
		}
	}, 0)
	return value
}

func ContainerFromBorrowHandle(handleValue int32) *Container {
	handle := witRuntime.MakeHandle(handleValue)
	return &Container{handle}
}

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [async-lower][method]container.name
func wasm_import_method_container_name(arg0 int32, arg1 uintptr) int32

func (self *Container) Name() witTypes.Result[string, wasmcloud_blobstore_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_method_container_name((self).Handle(), returnArea)))
	var result witTypes.Result[string, wasmcloud_blobstore_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Ok[string, wasmcloud_blobstore_0_1_0_types.Error](value)
	case 1:
		var variant wasmcloud_blobstore_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchContainer()

		case 1:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorContainerAlreadyExists()

		case 2:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchObject()

		case 3:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorAccessDenied()

		case 4:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorOther(value0)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[string, wasmcloud_blobstore_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [async-lower][method]container.info
func wasm_import_method_container_info(arg0 int32, arg1 uintptr) int32

func (self *Container) Info() witTypes.Result[wasmcloud_blobstore_0_1_0_types.ContainerMetadata, wasmcloud_blobstore_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_container_info((self).Handle(), returnArea)))
	var result witTypes.Result[wasmcloud_blobstore_0_1_0_types.ContainerMetadata, wasmcloud_blobstore_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))

		result = witTypes.Ok[wasmcloud_blobstore_0_1_0_types.ContainerMetadata, wasmcloud_blobstore_0_1_0_types.Error](wasmcloud_blobstore_0_1_0_types.ContainerMetadata{value, uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))})
	case 1:
		var variant wasmcloud_blobstore_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchContainer()

		case 1:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorContainerAlreadyExists()

		case 2:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchObject()

		case 3:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorAccessDenied()

		case 4:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorOther(value0)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[wasmcloud_blobstore_0_1_0_types.ContainerMetadata, wasmcloud_blobstore_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [async-lower][method]container.get-data
func wasm_import_method_container_get_data(arg0 uintptr, arg1 uintptr) int32

func (self *Container) GetData(name string, start uint64, end uint64) witTypes.Result[*witTypes.StreamReader[uint8], wasmcloud_blobstore_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	params := witRuntime.Allocate(pinner, (24 + 2*4), 8)
	*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 0)) = (self).Handle()
	utf8 := unsafe.Pointer(unsafe.StringData(name))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 4)) = uint32(uint32(len(name)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 0)) = uint32(uintptr(uintptr(utf8)))
	*(*int64)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (8+2*4))), 0)) = int64(start)
	*(*int64)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (16+2*4))), 0)) = int64(end)

	witAsync.SubtaskWait(uint32(wasm_import_method_container_get_data(uintptr(params), returnArea)))
	var result witTypes.Result[*witTypes.StreamReader[uint8], wasmcloud_blobstore_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*witTypes.StreamReader[uint8], wasmcloud_blobstore_0_1_0_types.Error](LiftStreamU8(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))
	case 1:
		var variant wasmcloud_blobstore_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchContainer()

		case 1:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorContainerAlreadyExists()

		case 2:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchObject()

		case 3:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorAccessDenied()

		case 4:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*witTypes.StreamReader[uint8], wasmcloud_blobstore_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [async-lower][method]container.write-data
func wasm_import_method_container_write_data(arg0 int32, arg1 uintptr, arg2 uint32, arg3 int32, arg4 uintptr) int32

func (self *Container) WriteData(name string, data *witTypes.StreamReader[uint8]) witTypes.Result[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(name))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_method_container_write_data((self).Handle(), uintptr(utf8), uint32(len(name)), (data).TakeHandle(), returnArea)))
	var result witTypes.Result[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error](witTypes.Unit{})
	case 1:
		var variant wasmcloud_blobstore_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchContainer()

		case 1:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorContainerAlreadyExists()

		case 2:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchObject()

		case 3:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorAccessDenied()

		case 4:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [async-lower][method]container.list-objects
func wasm_import_method_container_list_objects(arg0 int32, arg1 uintptr) int32

func (self *Container) ListObjects() witTypes.Result[*witTypes.StreamReader[string], wasmcloud_blobstore_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_method_container_list_objects((self).Handle(), returnArea)))
	var result witTypes.Result[*witTypes.StreamReader[string], wasmcloud_blobstore_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*witTypes.StreamReader[string], wasmcloud_blobstore_0_1_0_types.Error](LiftStreamString(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))
	case 1:
		var variant wasmcloud_blobstore_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchContainer()

		case 1:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorContainerAlreadyExists()

		case 2:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchObject()

		case 3:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorAccessDenied()

		case 4:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*witTypes.StreamReader[string], wasmcloud_blobstore_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [async-lower][method]container.delete-object
func wasm_import_method_container_delete_object(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr) int32

func (self *Container) DeleteObject(name string) witTypes.Result[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(name))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_method_container_delete_object((self).Handle(), uintptr(utf8), uint32(len(name)), returnArea)))
	var result witTypes.Result[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error](witTypes.Unit{})
	case 1:
		var variant wasmcloud_blobstore_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchContainer()

		case 1:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorContainerAlreadyExists()

		case 2:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchObject()

		case 3:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorAccessDenied()

		case 4:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [async-lower][method]container.delete-objects
func wasm_import_method_container_delete_objects(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr) int32

func (self *Container) DeleteObjects(names []string) witTypes.Result[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	slice := names
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(2*4))
		utf8 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))

	}

	witAsync.SubtaskWait(uint32(wasm_import_method_container_delete_objects((self).Handle(), uintptr(result), length, returnArea)))
	var result0 witTypes.Result[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result0 = witTypes.Ok[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error](witTypes.Unit{})
	case 1:
		var variant wasmcloud_blobstore_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchContainer()

		case 1:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorContainerAlreadyExists()

		case 2:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchObject()

		case 3:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorAccessDenied()

		case 4:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result0 = witTypes.Err[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result0

}

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [async-lower][method]container.has-object
func wasm_import_method_container_has_object(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr) int32

func (self *Container) HasObject(name string) witTypes.Result[bool, wasmcloud_blobstore_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(name))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_method_container_has_object((self).Handle(), uintptr(utf8), uint32(len(name)), returnArea)))
	var result witTypes.Result[bool, wasmcloud_blobstore_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[bool, wasmcloud_blobstore_0_1_0_types.Error]((uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) != 0))
	case 1:
		var variant wasmcloud_blobstore_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchContainer()

		case 1:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorContainerAlreadyExists()

		case 2:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchObject()

		case 3:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorAccessDenied()

		case 4:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[bool, wasmcloud_blobstore_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [async-lower][method]container.object-info
func wasm_import_method_container_object_info(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr) int32

func (self *Container) ObjectInfo(name string) witTypes.Result[wasmcloud_blobstore_0_1_0_types.ObjectMetadata, wasmcloud_blobstore_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (24 + 4*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(name))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_method_container_object_info((self).Handle(), uintptr(utf8), uint32(len(name)), returnArea)))
	var result witTypes.Result[wasmcloud_blobstore_0_1_0_types.ObjectMetadata, wasmcloud_blobstore_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))
		value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 3*4))))

		result = witTypes.Ok[wasmcloud_blobstore_0_1_0_types.ObjectMetadata, wasmcloud_blobstore_0_1_0_types.Error](wasmcloud_blobstore_0_1_0_types.ObjectMetadata{value, value0, uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 4*4)))), uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 4*4))))})
	case 1:
		var variant wasmcloud_blobstore_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchContainer()

		case 1:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorContainerAlreadyExists()

		case 2:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchObject()

		case 3:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorAccessDenied()

		case 4:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorOther(value1)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[wasmcloud_blobstore_0_1_0_types.ObjectMetadata, wasmcloud_blobstore_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:blobstore/container@0.1.0 [async-lower][method]container.clear
func wasm_import_method_container_clear(arg0 int32, arg1 uintptr) int32

func (self *Container) Clear() witTypes.Result[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_method_container_clear((self).Handle(), returnArea)))
	var result witTypes.Result[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error](witTypes.Unit{})
	case 1:
		var variant wasmcloud_blobstore_0_1_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchContainer()

		case 1:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorContainerAlreadyExists()

		case 2:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorNoSuchObject()

		case 3:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorAccessDenied()

		case 4:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_blobstore_0_1_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, wasmcloud_blobstore_0_1_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}
