// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:component-go@0.2.0
//     componentize-go:union

package wasi_sockets_0_2_8_udp_create_socket

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"go.wasmcloud.dev/component/imports/wasi_sockets_0_2_8_network"
	"go.wasmcloud.dev/component/imports/wasi_sockets_0_2_8_udp"
	"runtime"
	"unsafe"
)

type Network = wasi_sockets_0_2_8_network.Network
type ErrorCode = wasi_sockets_0_2_8_network.ErrorCode
type IpAddressFamily = wasi_sockets_0_2_8_network.IpAddressFamily
type UdpSocket = wasi_sockets_0_2_8_udp.UdpSocket

//go:wasmimport wasi:sockets/udp-create-socket@0.2.8 create-udp-socket
func wasm_import_create_udp_socket(arg0 int32, arg1 uintptr)

func CreateUdpSocket(addressFamily wasi_sockets_0_2_8_network.IpAddressFamily) witTypes.Result[*wasi_sockets_0_2_8_udp.UdpSocket, wasi_sockets_0_2_8_network.ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	wasm_import_create_udp_socket(int32(addressFamily), returnArea)
	var result witTypes.Result[*wasi_sockets_0_2_8_udp.UdpSocket, wasi_sockets_0_2_8_network.ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*wasi_sockets_0_2_8_udp.UdpSocket, wasi_sockets_0_2_8_network.ErrorCode](wasi_sockets_0_2_8_udp.UdpSocketFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:

		result = witTypes.Err[*wasi_sockets_0_2_8_udp.UdpSocket, wasi_sockets_0_2_8_network.ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}
