// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:component-go@0.2.0
//     componentize-go:union

package wasi_clocks_0_3_0_monotonic_clock

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
)

type Duration = uint64
type Mark = uint64

//go:wasmimport wasi:clocks/monotonic-clock@0.3.0 now
func wasm_import_now() int64

func Now() uint64 {

	result := wasm_import_now()
	return uint64(result)

}

//go:wasmimport wasi:clocks/monotonic-clock@0.3.0 get-resolution
func wasm_import_get_resolution() int64

func GetResolution() uint64 {

	result := wasm_import_get_resolution()
	return uint64(result)

}

//go:wasmimport wasi:clocks/monotonic-clock@0.3.0 [async-lower]wait-until
func wasm_import_wait_until(arg0 int64) int32

func WaitUntil(when uint64) {

	witAsync.SubtaskWait(uint32(wasm_import_wait_until(int64(when))))

}

//go:wasmimport wasi:clocks/monotonic-clock@0.3.0 [async-lower]wait-for
func wasm_import_wait_for(arg0 int64) int32

func WaitFor(howLong uint64) {

	witAsync.SubtaskWait(uint32(wasm_import_wait_for(int64(howLong))))

}
