// Generated by `wit-bindgen` 0.61.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.1.0
//     wasmcloud:keyvalue@0.2.0
//     wasmcloud:messaging@0.3.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_messaging_0_3_0_consumer

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"go.wasmcloud.dev/component/imports/wasmcloud_messaging_0_3_0_types"
	"runtime"
	"unsafe"
)

//go:wasmimport wasmcloud:messaging/consumer@0.3.0 [stream-new-0]request
func wasm_stream_new_u8() uint64

//go:wasmimport wasmcloud:messaging/consumer@0.3.0 [async-lower][stream-read-0]request
func wasm_stream_read_u8(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport wasmcloud:messaging/consumer@0.3.0 [async-lower][stream-write-0]request
func wasm_stream_write_u8(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport wasmcloud:messaging/consumer@0.3.0 [stream-drop-readable-0]request
func wasm_stream_drop_readable_u8(handle int32)

//go:wasmimport wasmcloud:messaging/consumer@0.3.0 [stream-drop-writable-0]request
func wasm_stream_drop_writable_u8(handle int32)

var wasm_stream_vtable_u8 = witTypes.StreamVtable[uint8]{
	Size:         1,
	Align:        1,
	Read:         wasm_stream_read_u8,
	Write:        wasm_stream_write_u8,
	CancelRead:   nil,
	CancelWrite:  nil,
	DropReadable: wasm_stream_drop_readable_u8,
	DropWritable: wasm_stream_drop_writable_u8,
	Lift:         nil,
	Lower:        nil,
}

func MakeStreamU8() (*witTypes.StreamWriter[uint8], *witTypes.StreamReader[uint8]) {
	pair := wasm_stream_new_u8()
	return witTypes.MakeStreamWriter[uint8](&wasm_stream_vtable_u8, int32(pair>>32)),
		witTypes.MakeStreamReader[uint8](&wasm_stream_vtable_u8, int32(pair&0xFFFFFFFF))
}

func LiftStreamU8(handle int32) *witTypes.StreamReader[uint8] {
	return witTypes.MakeStreamReader[uint8](&wasm_stream_vtable_u8, handle)
}

type BrokerMessage = wasmcloud_messaging_0_3_0_types.BrokerMessage
type Error = wasmcloud_messaging_0_3_0_types.Error

//go:wasmimport wasmcloud:messaging/consumer@0.3.0 [async-lower]request
func wasm_import_request(arg0 uintptr, arg1 uintptr) int32

func Request(subject string, body *witTypes.StreamReader[uint8], timeoutMs witTypes.Option[uint32]) witTypes.Result[wasmcloud_messaging_0_3_0_types.BrokerMessage, wasmcloud_messaging_0_3_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (7 * 4), 4))
	params := witRuntime.Allocate(pinner, (8 + 3*4), 4)
	utf8 := unsafe.Pointer(unsafe.StringData(subject))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 4)) = uint32(uint32(len(subject)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 0)) = uint32(uintptr(uintptr(utf8)))
	*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (2*4))), 0)) = (body).TakeHandle()

	switch timeoutMs.Tag() {
	case witTypes.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (4+2*4))), 0)) = int8(int32(0))

	case witTypes.OptionSome:
		payload := timeoutMs.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (4+2*4))), 0)) = int8(int32(1))
		*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (4+2*4))), 4)) = int32(payload)

	default:
		panic("unreachable")
	}

	witAsync.SubtaskWait(uint32(wasm_import_request(uintptr(params), returnArea)))
	var result witTypes.Result[wasmcloud_messaging_0_3_0_types.BrokerMessage, wasmcloud_messaging_0_3_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		var option witTypes.Option[string]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))) {
		case 0:

			option = witTypes.None[string]()
		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4))))

			option = witTypes.Some[string](value0)
		default:
			panic("unreachable")
		}

		result = witTypes.Ok[wasmcloud_messaging_0_3_0_types.BrokerMessage, wasmcloud_messaging_0_3_0_types.Error](wasmcloud_messaging_0_3_0_types.BrokerMessage{Subject: value, Body: LiftStreamU8(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4)))), ReplyTo: option})
	case 1:
		var variant wasmcloud_messaging_0_3_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_messaging_0_3_0_types.MakeErrorSubjectInvalid()

		case 1:

			variant = wasmcloud_messaging_0_3_0_types.MakeErrorAccessDenied()

		case 2:

			variant = wasmcloud_messaging_0_3_0_types.MakeErrorTimeout()

		case 3:

			variant = wasmcloud_messaging_0_3_0_types.MakeErrorBrokerUnavailable()

		case 4:

			variant = wasmcloud_messaging_0_3_0_types.MakeErrorMessageTooLarge()

		case 5:

			variant = wasmcloud_messaging_0_3_0_types.MakeErrorQuotaExceeded()

		case 6:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_messaging_0_3_0_types.MakeErrorOther(value1)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[wasmcloud_messaging_0_3_0_types.BrokerMessage, wasmcloud_messaging_0_3_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:messaging/consumer@0.3.0 [async-lower]publish
func wasm_import_publish(arg0 uintptr, arg1 uintptr) int32

func Publish(msg wasmcloud_messaging_0_3_0_types.BrokerMessage) witTypes.Result[witTypes.Unit, wasmcloud_messaging_0_3_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	params := witRuntime.Allocate(pinner, (6 * 4), 4)
	utf8 := unsafe.Pointer(unsafe.StringData((msg).Subject))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 4)) = uint32(uint32(len((msg).Subject)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 0)) = uint32(uintptr(uintptr(utf8)))
	*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (2 * 4))) = ((msg).Body).TakeHandle()

	switch (msg).ReplyTo.Tag() {
	case witTypes.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (3 * 4))) = int8(int32(0))

	case witTypes.OptionSome:
		payload := (msg).ReplyTo.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (3 * 4))) = int8(int32(1))
		utf80 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf80)
		*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (5 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), (4 * 4))) = uint32(uintptr(uintptr(utf80)))

	default:
		panic("unreachable")
	}

	witAsync.SubtaskWait(uint32(wasm_import_publish(uintptr(params), returnArea)))
	var result witTypes.Result[witTypes.Unit, wasmcloud_messaging_0_3_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, wasmcloud_messaging_0_3_0_types.Error](witTypes.Unit{})
	case 1:
		var variant wasmcloud_messaging_0_3_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_messaging_0_3_0_types.MakeErrorSubjectInvalid()

		case 1:

			variant = wasmcloud_messaging_0_3_0_types.MakeErrorAccessDenied()

		case 2:

			variant = wasmcloud_messaging_0_3_0_types.MakeErrorTimeout()

		case 3:

			variant = wasmcloud_messaging_0_3_0_types.MakeErrorBrokerUnavailable()

		case 4:

			variant = wasmcloud_messaging_0_3_0_types.MakeErrorMessageTooLarge()

		case 5:

			variant = wasmcloud_messaging_0_3_0_types.MakeErrorQuotaExceeded()

		case 6:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_messaging_0_3_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, wasmcloud_messaging_0_3_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result

}
