// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:component-go@0.2.0
//     componentize-go:union

package wasi_io_0_2_8_poll

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"runtime"
	"unsafe"
)

//go:wasmimport wasi:io/poll@0.2.8 [resource-drop]pollable
func resourceDropPollable(handle int32)

type Pollable struct {
	handle *witRuntime.Handle
}

func (self *Pollable) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Pollable) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Pollable) Handle() int32 {
	return self.handle.Use()
}

func (self *Pollable) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropPollable(handle)
	}
}

func PollableFromOwnHandle(handleValue int32) *Pollable {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Pollable{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropPollable(handleValue)
		}
	}, 0)
	return value
}

func PollableFromBorrowHandle(handleValue int32) *Pollable {
	handle := witRuntime.MakeHandle(handleValue)
	return &Pollable{handle}
}

//go:wasmimport wasi:io/poll@0.2.8 [method]pollable.ready
func wasm_import_method_pollable_ready(arg0 int32) int32

func (self *Pollable) Ready() bool {

	result := wasm_import_method_pollable_ready((self).Handle())
	return (result != 0)

}

//go:wasmimport wasi:io/poll@0.2.8 [method]pollable.block
func wasm_import_method_pollable_block(arg0 int32)

func (self *Pollable) Block() {

	wasm_import_method_pollable_block((self).Handle())

}

//go:wasmimport wasi:io/poll@0.2.8 poll
func wasm_import_poll(arg0 uintptr, arg1 uint32, arg2 uintptr)

func Poll(in []*Pollable) []uint32 {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	slice := in
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*4), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*4)
		*(*int32)(unsafe.Add(unsafe.Pointer(base), 0)) = (element).Handle()

	}

	wasm_import_poll(uintptr(result), length, returnArea)
	value := unsafe.Slice((*uint32)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result0 := value
	return result0

}
