// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:component-go@0.2.0
//     componentize-go:union

package wasi_sockets_0_2_8_ip_name_lookup

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"go.wasmcloud.dev/component/imports/wasi_io_0_2_8_poll"
	"go.wasmcloud.dev/component/imports/wasi_sockets_0_2_8_network"
	"runtime"
	"unsafe"
)

type Pollable = wasi_io_0_2_8_poll.Pollable
type Network = wasi_sockets_0_2_8_network.Network
type ErrorCode = wasi_sockets_0_2_8_network.ErrorCode
type IpAddress = wasi_sockets_0_2_8_network.IpAddress

//go:wasmimport wasi:sockets/ip-name-lookup@0.2.8 [resource-drop]resolve-address-stream
func resourceDropResolveAddressStream(handle int32)

type ResolveAddressStream struct {
	handle *witRuntime.Handle
}

func (self *ResolveAddressStream) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *ResolveAddressStream) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *ResolveAddressStream) Handle() int32 {
	return self.handle.Use()
}

func (self *ResolveAddressStream) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropResolveAddressStream(handle)
	}
}

func ResolveAddressStreamFromOwnHandle(handleValue int32) *ResolveAddressStream {
	handle := witRuntime.MakeHandle(handleValue)
	value := &ResolveAddressStream{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropResolveAddressStream(handleValue)
		}
	}, 0)
	return value
}

func ResolveAddressStreamFromBorrowHandle(handleValue int32) *ResolveAddressStream {
	handle := witRuntime.MakeHandle(handleValue)
	return &ResolveAddressStream{handle}
}

//go:wasmimport wasi:sockets/ip-name-lookup@0.2.8 [method]resolve-address-stream.resolve-next-address
func wasm_import_method_resolve_address_stream_resolve_next_address(arg0 int32, arg1 uintptr)

func (self *ResolveAddressStream) ResolveNextAddress() witTypes.Result[witTypes.Option[wasi_sockets_0_2_8_network.IpAddress], wasi_sockets_0_2_8_network.ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 22, 2))
	wasm_import_method_resolve_address_stream_resolve_next_address((self).Handle(), returnArea)
	var result witTypes.Result[witTypes.Option[wasi_sockets_0_2_8_network.IpAddress], wasi_sockets_0_2_8_network.ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		var option witTypes.Option[wasi_sockets_0_2_8_network.IpAddress]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 2))) {
		case 0:

			option = witTypes.None[wasi_sockets_0_2_8_network.IpAddress]()
		case 1:
			var variant wasi_sockets_0_2_8_network.IpAddress
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
			case 0:

				variant = wasi_sockets_0_2_8_network.MakeIpAddressIpv4(witTypes.Tuple4[uint8, uint8, uint8, uint8]{uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 6)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 7)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 9))))})

			case 1:

				variant = wasi_sockets_0_2_8_network.MakeIpAddressIpv6(witTypes.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 6)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 10)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 12)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 14)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 18)))), uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 20))))})

			default:
				panic("unreachable")
			}

			option = witTypes.Some[wasi_sockets_0_2_8_network.IpAddress](variant)
		default:
			panic("unreachable")
		}

		result = witTypes.Ok[witTypes.Option[wasi_sockets_0_2_8_network.IpAddress], wasi_sockets_0_2_8_network.ErrorCode](option)
	case 1:

		result = witTypes.Err[witTypes.Option[wasi_sockets_0_2_8_network.IpAddress], wasi_sockets_0_2_8_network.ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 2)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:sockets/ip-name-lookup@0.2.8 [method]resolve-address-stream.subscribe
func wasm_import_method_resolve_address_stream_subscribe(arg0 int32) int32

func (self *ResolveAddressStream) Subscribe() *wasi_io_0_2_8_poll.Pollable {

	result := wasm_import_method_resolve_address_stream_subscribe((self).Handle())
	return wasi_io_0_2_8_poll.PollableFromOwnHandle(int32(uintptr(result)))

}

//go:wasmimport wasi:sockets/ip-name-lookup@0.2.8 resolve-addresses
func wasm_import_resolve_addresses(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func ResolveAddresses(network *wasi_sockets_0_2_8_network.Network, name string) witTypes.Result[*ResolveAddressStream, wasi_sockets_0_2_8_network.ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	utf8 := unsafe.Pointer(unsafe.StringData(name))
	pinner.Pin(utf8)
	wasm_import_resolve_addresses((network).Handle(), uintptr(utf8), uint32(len(name)), returnArea)
	var result witTypes.Result[*ResolveAddressStream, wasi_sockets_0_2_8_network.ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*ResolveAddressStream, wasi_sockets_0_2_8_network.ErrorCode](ResolveAddressStreamFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:

		result = witTypes.Err[*ResolveAddressStream, wasi_sockets_0_2_8_network.ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}
