// Generated by `wit-bindgen` 0.61.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasmcloud:host@0.1.3
//     wasmcloud:plugin-go@0.1.0
//     componentize-go:union

package wasmcloud_host_0_1_3_workload_call

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

type WorkloadId = string

//go:wasmimport wasmcloud:host/workload-call@0.1.3 [resource-drop]target
func resourceDropTarget(handle int32)

// One workload, on one interface of it, that this task's calls go to for as
// long as the handle is alive.
//
// A handle is per interface, not per workload, because a workload need only
// export some of what a plugin imports. Binding both together is what makes
// the pairing checkable when it is made rather than when it is used: a
// handle exists only if that workload really serves that interface, so
// holding one is proof the call can be routed.
//
// Handles nest per interface: the innermost live handle *for the interface
// being called* wins, and dropping it restores the one it shadowed. A
// handle for one interface does not redirect calls on another — those fall
// back to the workload whose capability call this task is serving, the same
// as if no handle were held, so a plugin calling back into its own caller
// needs no handle at all.
//
// A handle also pins *which* component serves the interface, so a call it
// scopes cannot be moved to another mid-dispatch. It does not pin the
// workload: one held past the workload's stop — or past a redeploy under
// the same id, which is a different workload as far as this interface is
// concerned — answers `not-running` on the next call through it. Open a
// handle for the work at hand rather than stashing one.
type Target struct {
	handle *witRuntime.Handle
}

func (self *Target) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Target) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Target) Handle() int32 {
	return self.handle.Use()
}

func (self *Target) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropTarget(handle)
	}
}

func TargetFromOwnHandle(handleValue int32) *Target {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Target{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropTarget(handleValue)
		}
	}, 0)
	return value
}

func TargetFromBorrowHandle(handleValue int32) *Target {
	handle := witRuntime.MakeHandle(handleValue)
	return &Target{handle}
}

//go:wasmimport wasmcloud:host/workload-call@0.1.3 [static]target.open
func wasm_import_static_target_open(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr)

func TargetOpen(id string, interface_ string) witTypes.Option[*Target] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	utf8 := unsafe.Pointer(unsafe.StringData(id))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(interface_))
	pinner.Pin(utf80)
	wasm_import_static_target_open(uintptr(utf8), uint32(len(id)), uintptr(utf80), uint32(len(interface_)), returnArea)
	var option witTypes.Option[*Target]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[*Target]()
	case 1:

		option = witTypes.Some[*Target](TargetFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	default:
		panic("unreachable")
	}
	result := option
	return result

}

//go:wasmimport wasmcloud:host/workload-call@0.1.3 [method]target.get-workload-id
func wasm_import_method_target_get_workload_id(arg0 int32, arg1 uintptr)

func (self *Target) GetWorkloadId() string {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_target_get_workload_id((self).Handle(), returnArea)
	value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := value
	return result

}

//go:wasmimport wasmcloud:host/workload-call@0.1.3 [method]target.get-interface
func wasm_import_method_target_get_interface(arg0 int32, arg1 uintptr)

func (self *Target) GetInterface() string {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_target_get_interface((self).Handle(), returnArea)
	value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := value
	return result

}

//go:wasmimport wasmcloud:host/workload-call@0.1.3 callable
func wasm_import_callable(arg0 uintptr)

func Callable() map[string][]string {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_callable(returnArea)
	result1 := make(map[string][]string, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0)))), index*(4*4))
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
		result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))))), index*(2*4))
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, value0)
		}

		result1[value] = result
	}

	result2 := result1
	return result2

}
