// Generated by `wit-bindgen` 0.61.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.1.0
//     wasmcloud:keyvalue@0.2.0
//     wasmcloud:messaging@0.3.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_keyvalue_0_2_0_types

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

const (
	// The host does not recognize the store identifier requested.
	ErrorNoSuchStore uint8 = 0
	// The requesting component does not have access to the specified store
	// (which may or may not exist).
	ErrorAccessDenied uint8 = 1
	// The request was malformed or self-contradictory, e.g. a `cas.swap`
	// whose `cas-options` sets no precondition.
	ErrorInvalidArgument uint8 = 2
	// A conditional operation did not meet its precondition, e.g. a `set` with
	// `if-not-exists` against a key that already exists.
	ErrorPreconditionFailed uint8 = 3
	// The operation did not complete within the host- or backend-imposed time
	// limit.
	ErrorTimeout uint8 = 4
	// The store is currently unreachable or otherwise unavailable. The
	// operation may succeed if retried later.
	ErrorStoreUnavailable uint8 = 5
	// The operation was rejected because a quota or rate limit was exceeded.
	ErrorQuotaExceeded uint8 = 6
	// Some other implementation-specific error has occurred (e.g. I/O). Used
	// for backend-specific failures that do not map to a named case above.
	ErrorOther uint8 = 7
)

// The set of errors which may be raised by functions in this package.
//
// Following the wasip3 convention, this enumerates specific named cases
// rather than leaning on stringly-typed errors. It is intentionally
// non-exhaustive: future versions may add cases, and generated bindings are
// marked non-exhaustive accordingly, so consumers must always include a
// catch-all arm. Backend-specific failures that do not map to a named case
// are reported via `other`.
type Error struct {
	tag   uint8
	value any
}

func (self Error) Tag() uint8 {
	return self.tag
}

func (self Error) Other() string {
	if self.tag != ErrorOther {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeErrorNoSuchStore() Error {
	return Error{ErrorNoSuchStore, nil}
}
func MakeErrorAccessDenied() Error {
	return Error{ErrorAccessDenied, nil}
}
func MakeErrorInvalidArgument() Error {
	return Error{ErrorInvalidArgument, nil}
}
func MakeErrorPreconditionFailed() Error {
	return Error{ErrorPreconditionFailed, nil}
}
func MakeErrorTimeout() Error {
	return Error{ErrorTimeout, nil}
}
func MakeErrorStoreUnavailable() Error {
	return Error{ErrorStoreUnavailable, nil}
}
func MakeErrorQuotaExceeded() Error {
	return Error{ErrorQuotaExceeded, nil}
}
func MakeErrorOther(value string) Error {
	return Error{ErrorOther, value}
}

// A response to a `list-keys` operation.
type KeyResponse struct {
	// The list of keys returned by the query.
	Keys []string
	// The continuation token to use to fetch the next page of keys. If this is `none`, then
	// there are no more keys to fetch.
	Cursor witTypes.Option[string]
}

// Options that modify the behavior of a `set` operation.
type SetOptions struct {
	// If set, the entry expires this many milliseconds after the write, after
	// which the host removes it. `none` stores the entry without expiry.
	//
	// Hosts whose backend cannot honor expiry MUST raise an error rather than
	// silently ignoring the TTL.
	TtlMs witTypes.Option[uint64]
	// When true, the write succeeds only if the key does not already exist,
	// failing with `error::precondition-failed` otherwise. Useful for locks
	// and idempotent initialization.
	IfNotExists bool
}

//go:wasmimport wasmcloud:keyvalue/types@0.2.0 [resource-drop]bucket
func resourceDropBucket(handle int32)

// A bucket is a collection of key-value pairs. Each key-value pair is stored as an entry in the
// bucket, and the bucket itself acts as a collection of all these entries.
//
// It is worth noting that the exact terminology for bucket in key-value stores can vary
// depending on the specific implementation. For example:
//
// 1. Amazon DynamoDB calls a collection of key-value pairs a table
// 2. Redis has hashes, sets, and sorted sets as different types of collections
// 3. Cassandra calls a collection of key-value pairs a column family
// 4. MongoDB calls a collection of key-value pairs a collection
// 5. Riak calls a collection of key-value pairs a bucket
// 6. Memcached calls a collection of key-value pairs a slab
// 7. Azure Cosmos DB calls a collection of key-value pairs a container
//
// In this interface, we use the term `bucket` to refer to a collection of key-value pairs
type Bucket struct {
	handle *witRuntime.Handle
}

func (self *Bucket) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Bucket) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Bucket) Handle() int32 {
	return self.handle.Use()
}

func (self *Bucket) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropBucket(handle)
	}
}

func BucketFromOwnHandle(handleValue int32) *Bucket {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Bucket{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropBucket(handleValue)
		}
	}, 0)
	return value
}

func BucketFromBorrowHandle(handleValue int32) *Bucket {
	handle := witRuntime.MakeHandle(handleValue)
	return &Bucket{handle}
}

//go:wasmimport wasmcloud:keyvalue/types@0.2.0 [async-lower][method]bucket.get
func wasm_import_method_bucket_get(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr) int32

func (self *Bucket) Get(key string) witTypes.Result[witTypes.Option[[]uint8], Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_method_bucket_get((self).Handle(), uintptr(utf8), uint32(len(key)), returnArea)))
	var result witTypes.Result[witTypes.Option[[]uint8], Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		var option witTypes.Option[[]uint8]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			option = witTypes.None[[]uint8]()
		case 1:
			value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			option = witTypes.Some[[]uint8](value)
		default:
			panic("unreachable")
		}

		result = witTypes.Ok[witTypes.Option[[]uint8], Error](option)
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorNoSuchStore()

		case 1:

			variant = MakeErrorAccessDenied()

		case 2:

			variant = MakeErrorInvalidArgument()

		case 3:

			variant = MakeErrorPreconditionFailed()

		case 4:

			variant = MakeErrorTimeout()

		case 5:

			variant = MakeErrorStoreUnavailable()

		case 6:

			variant = MakeErrorQuotaExceeded()

		case 7:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value0)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Option[[]uint8], Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:keyvalue/types@0.2.0 [async-lower][method]bucket.set
func wasm_import_method_bucket_set(arg0 uintptr, arg1 uintptr) int32

func (self *Bucket) Set(key string, value []uint8, options witTypes.Option[SetOptions]) witTypes.Result[witTypes.Unit, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	params := witRuntime.Allocate(pinner, (40 + 4*4), 8)
	*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 0)) = (self).Handle()
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 4)) = uint32(uint32(len(key)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 0)) = uint32(uintptr(uintptr(utf8)))
	data := unsafe.Pointer(unsafe.SliceData(value))
	pinner.Pin(data)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 4)) = uint32(uint32(len(value)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 0)) = uint32(uintptr(uintptr(data)))

	switch options.Tag() {
	case witTypes.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (8+4*4))), 0)) = int8(int32(0))

	case witTypes.OptionSome:
		payload := options.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (8+4*4))), 0)) = int8(int32(1))

		switch (payload).TtlMs.Tag() {
		case witTypes.OptionNone:
			*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (8+4*4))), 8)) = int8(int32(0))

		case witTypes.OptionSome:
			payload := (payload).TtlMs.Some()
			*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (8+4*4))), 8)) = int8(int32(1))
			*(*int64)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (8+4*4))), 16)) = int64(payload)

		default:
			panic("unreachable")
		}
		var result int32
		if (payload).IfNotExists {
			result = 1
		} else {
			result = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (8+4*4))), 24)) = int8(result)

	default:
		panic("unreachable")
	}

	witAsync.SubtaskWait(uint32(wasm_import_method_bucket_set(uintptr(params), returnArea)))
	var result1 witTypes.Result[witTypes.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result1 = witTypes.Ok[witTypes.Unit, Error](witTypes.Unit{})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorNoSuchStore()

		case 1:

			variant = MakeErrorAccessDenied()

		case 2:

			variant = MakeErrorInvalidArgument()

		case 3:

			variant = MakeErrorPreconditionFailed()

		case 4:

			variant = MakeErrorTimeout()

		case 5:

			variant = MakeErrorStoreUnavailable()

		case 6:

			variant = MakeErrorQuotaExceeded()

		case 7:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value0)

		default:
			panic("unreachable")
		}

		result1 = witTypes.Err[witTypes.Unit, Error](variant)
	default:
		panic("unreachable")
	}

	return result1

}

//go:wasmimport wasmcloud:keyvalue/types@0.2.0 [async-lower][method]bucket.delete
func wasm_import_method_bucket_delete(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr) int32

func (self *Bucket) Delete(key string) witTypes.Result[witTypes.Unit, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_method_bucket_delete((self).Handle(), uintptr(utf8), uint32(len(key)), returnArea)))
	var result witTypes.Result[witTypes.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, Error](witTypes.Unit{})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorNoSuchStore()

		case 1:

			variant = MakeErrorAccessDenied()

		case 2:

			variant = MakeErrorInvalidArgument()

		case 3:

			variant = MakeErrorPreconditionFailed()

		case 4:

			variant = MakeErrorTimeout()

		case 5:

			variant = MakeErrorStoreUnavailable()

		case 6:

			variant = MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:keyvalue/types@0.2.0 [async-lower][method]bucket.exists
func wasm_import_method_bucket_exists(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr) int32

func (self *Bucket) Exists(key string) witTypes.Result[bool, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_method_bucket_exists((self).Handle(), uintptr(utf8), uint32(len(key)), returnArea)))
	var result witTypes.Result[bool, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[bool, Error]((uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) != 0))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorNoSuchStore()

		case 1:

			variant = MakeErrorAccessDenied()

		case 2:

			variant = MakeErrorInvalidArgument()

		case 3:

			variant = MakeErrorPreconditionFailed()

		case 4:

			variant = MakeErrorTimeout()

		case 5:

			variant = MakeErrorStoreUnavailable()

		case 6:

			variant = MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[bool, Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport wasmcloud:keyvalue/types@0.2.0 [async-lower][method]bucket.list-keys
func wasm_import_method_bucket_list_keys(arg0 uintptr, arg1 uintptr) int32

func (self *Bucket) ListKeys(prefix witTypes.Option[string], cursor witTypes.Option[string]) witTypes.Result[KeyResponse, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (6 * 4), 4))
	params := witRuntime.Allocate(pinner, (7 * 4), 4)
	*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 0)) = (self).Handle()

	switch prefix.Tag() {
	case witTypes.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 0)) = int8(int32(0))

	case witTypes.OptionSome:
		payload := prefix.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 0)) = int8(int32(1))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 4)) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}

	switch cursor.Tag() {
	case witTypes.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (4*4))), 0)) = int8(int32(0))

	case witTypes.OptionSome:
		payload := cursor.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (4*4))), 0)) = int8(int32(1))
		utf80 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf80)
		*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (4*4))), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (4*4))), 4)) = uint32(uintptr(uintptr(utf80)))

	default:
		panic("unreachable")
	}

	witAsync.SubtaskWait(uint32(wasm_import_method_bucket_list_keys(uintptr(params), returnArea)))
	var result3 witTypes.Result[KeyResponse, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(2*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, value)
		}

		var option witTypes.Option[string]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4)))) {
		case 0:

			option = witTypes.None[string]()
		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))

			option = witTypes.Some[string](value1)
		default:
			panic("unreachable")
		}

		result3 = witTypes.Ok[KeyResponse, Error](KeyResponse{Keys: result, Cursor: option})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorNoSuchStore()

		case 1:

			variant = MakeErrorAccessDenied()

		case 2:

			variant = MakeErrorInvalidArgument()

		case 3:

			variant = MakeErrorPreconditionFailed()

		case 4:

			variant = MakeErrorTimeout()

		case 5:

			variant = MakeErrorStoreUnavailable()

		case 6:

			variant = MakeErrorQuotaExceeded()

		case 7:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value2)

		default:
			panic("unreachable")
		}

		result3 = witTypes.Err[KeyResponse, Error](variant)
	default:
		panic("unreachable")
	}

	return result3

}
