// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.0.0
//     wasmcloud:keyvalue@0.1.0
//     wasmcloud:messaging@0.2.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_postgres_0_2_0_prepared

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"go.wasmcloud.dev/component/imports/wasmcloud_postgres_0_2_0_types"
	"runtime"
	"unsafe"
)

type PgValue = wasmcloud_postgres_0_2_0_types.PgValue
type Error = wasmcloud_postgres_0_2_0_types.Error

// A token that represents a previously created prepared statement.
//
// This token can be expected to be somewhat opaque to users.
type PreparedStatementToken = string

//go:wasmimport wasmcloud:postgres/prepared@0.2.0 [async-lower]prepare
func wasm_import_prepare(arg0 uintptr, arg1 uint32, arg2 uintptr) int32

func Prepare(statement string) witTypes.Result[string, wasmcloud_postgres_0_2_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (13 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(statement))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_prepare(uintptr(utf8), uint32(len(statement)), returnArea)))
	var result11 witTypes.Result[string, wasmcloud_postgres_0_2_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result11 = witTypes.Ok[string, wasmcloud_postgres_0_2_0_types.Error](value)
	case 1:
		var variant wasmcloud_postgres_0_2_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorConnectionFailed(value0)

		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorInvalidParams(value1)

		case 2:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorInvalidQuery(value2)

		case 3:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))
			var option witTypes.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 * 4)))) {
			case 0:

				option = witTypes.None[string]()
			case 1:
				value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (9 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (10 * 4))))

				option = witTypes.Some[string](value6)
			default:
				panic("unreachable")
			}
			result := make([]witTypes.Tuple2[string, string], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (12 * 4))))
			for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (12 * 4)))); index++ {
				base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (11 * 4))))), index*(4*4))
				value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
				value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

				result = append(result, witTypes.Tuple2[string, string]{value7, value8})
			}

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorQueryFailed(wasmcloud_postgres_0_2_0_types.DbError{value3, value4, value5, option, result})

		case 4:
			value9 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorValueConversionFailed(value9)

		case 5:

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorUnknownPreparedStatement()

		case 6:

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorAccessDenied()

		case 7:

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorTimeout()

		case 8:
			value10 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorOther(value10)

		default:
			panic("unreachable")
		}

		result11 = witTypes.Err[string, wasmcloud_postgres_0_2_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result11

}

//go:wasmimport wasmcloud:postgres/prepared@0.2.0 [async-lower]exec
func wasm_import_exec(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr) int32

func Exec(stmtToken string, params []wasmcloud_postgres_0_2_0_types.PgValue) witTypes.Result[uint64, wasmcloud_postgres_0_2_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 + 12*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(stmtToken))
	pinner.Pin(utf8)
	slice168 := params
	length170 := uint32(len(slice168))
	result169 := witRuntime.Allocate(pinner, uintptr(length170*72), 8)
	for index, element := range slice168 {
		base := unsafe.Add(result169, index*72)

		switch element.Tag() {
		case wasmcloud_postgres_0_2_0_types.PgValueNull:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))

		case wasmcloud_postgres_0_2_0_types.PgValueBigInt:
			payload := element.BigInt()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case wasmcloud_postgres_0_2_0_types.PgValueInt8:
			payload := element.Int8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case wasmcloud_postgres_0_2_0_types.PgValueInt8Array:
			payload := element.Int8Array()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		case wasmcloud_postgres_0_2_0_types.PgValueBigSerial:
			payload := element.BigSerial()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case wasmcloud_postgres_0_2_0_types.PgValueSerial8:
			payload := element.Serial8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(5))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case wasmcloud_postgres_0_2_0_types.PgValueBool:
			payload := element.Bool()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(6))
			var result int32
			if payload {
				result = 1
			} else {
				result = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(result)

		case wasmcloud_postgres_0_2_0_types.PgValueBoolean:
			payload := element.Boolean()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(7))
			var result0 int32
			if payload {
				result0 = 1
			} else {
				result0 = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(result0)

		case wasmcloud_postgres_0_2_0_types.PgValueBoolArray:
			payload := element.BoolArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(8))
			slice := payload
			length := uint32(len(slice))
			result2 := witRuntime.Allocate(pinner, uintptr(length*1), 1)
			for index, element := range slice {
				base := unsafe.Add(result2, index*1)
				var result1 int32
				if element {
					result1 = 1
				} else {
					result1 = 0
				}
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(result1)

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result2)))

		case wasmcloud_postgres_0_2_0_types.PgValueDouble:
			payload := element.Double()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(9))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64((payload).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 16)) = int16(int32((payload).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 18)) = int8(int32((payload).F2))

		case wasmcloud_postgres_0_2_0_types.PgValueFloat8:
			payload := element.Float8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(10))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64((payload).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 16)) = int16(int32((payload).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 18)) = int8(int32((payload).F2))

		case wasmcloud_postgres_0_2_0_types.PgValueFloat8Array:
			payload := element.Float8Array()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(11))
			slice3 := payload
			length5 := uint32(len(slice3))
			result4 := witRuntime.Allocate(pinner, uintptr(length5*16), 8)
			for index, element := range slice3 {
				base := unsafe.Add(result4, index*16)
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)) = int64((element).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32((element).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32((element).F2))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length5)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result4)))

		case wasmcloud_postgres_0_2_0_types.PgValueReal:
			payload := element.Real()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(12))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64((payload).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 16)) = int16(int32((payload).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 18)) = int8(int32((payload).F2))

		case wasmcloud_postgres_0_2_0_types.PgValueFloat4:
			payload := element.Float4()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(13))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64((payload).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 16)) = int16(int32((payload).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 18)) = int8(int32((payload).F2))

		case wasmcloud_postgres_0_2_0_types.PgValueFloat4Array:
			payload := element.Float4Array()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(14))
			slice6 := payload
			length8 := uint32(len(slice6))
			result7 := witRuntime.Allocate(pinner, uintptr(length8*16), 8)
			for index, element := range slice6 {
				base := unsafe.Add(result7, index*16)
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)) = int64((element).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32((element).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32((element).F2))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length8)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result7)))

		case wasmcloud_postgres_0_2_0_types.PgValueInteger:
			payload := element.Integer()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(15))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case wasmcloud_postgres_0_2_0_types.PgValueInt:
			payload := element.Int()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(16))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case wasmcloud_postgres_0_2_0_types.PgValueInt4:
			payload := element.Int4()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(17))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case wasmcloud_postgres_0_2_0_types.PgValueInt4Array:
			payload := element.Int4Array()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(18))
			data9 := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data9)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data9)))

		case wasmcloud_postgres_0_2_0_types.PgValueNumeric:
			payload := element.Numeric()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(19))
			utf810 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf810)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf810)))

		case wasmcloud_postgres_0_2_0_types.PgValueDecimal:
			payload := element.Decimal()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(20))
			utf811 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf811)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf811)))

		case wasmcloud_postgres_0_2_0_types.PgValueNumericArray:
			payload := element.NumericArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(21))
			slice13 := payload
			length15 := uint32(len(slice13))
			result14 := witRuntime.Allocate(pinner, uintptr(length15*(2*4)), 4)
			for index, element := range slice13 {
				base := unsafe.Add(result14, index*(2*4))
				utf812 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf812)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf812)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length15)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result14)))

		case wasmcloud_postgres_0_2_0_types.PgValueSerial:
			payload := element.Serial()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(22))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32(payload)

		case wasmcloud_postgres_0_2_0_types.PgValueSerial4:
			payload := element.Serial4()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(23))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32(payload)

		case wasmcloud_postgres_0_2_0_types.PgValueSmallInt:
			payload := element.SmallInt()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(24))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case wasmcloud_postgres_0_2_0_types.PgValueInt2:
			payload := element.Int2()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(25))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case wasmcloud_postgres_0_2_0_types.PgValueInt2Array:
			payload := element.Int2Array()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(26))
			data16 := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data16)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data16)))

		case wasmcloud_postgres_0_2_0_types.PgValueInt2Vector:
			payload := element.Int2Vector()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(27))
			data17 := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data17)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data17)))

		case wasmcloud_postgres_0_2_0_types.PgValueInt2VectorArray:
			payload := element.Int2VectorArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(28))
			slice19 := payload
			length21 := uint32(len(slice19))
			result20 := witRuntime.Allocate(pinner, uintptr(length21*(2*4)), 4)
			for index, element := range slice19 {
				base := unsafe.Add(result20, index*(2*4))
				data18 := unsafe.Pointer(unsafe.SliceData(element))
				pinner.Pin(data18)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(data18)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length21)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result20)))

		case wasmcloud_postgres_0_2_0_types.PgValueSmallSerial:
			payload := element.SmallSerial()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(29))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case wasmcloud_postgres_0_2_0_types.PgValueSerial2:
			payload := element.Serial2()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(30))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case wasmcloud_postgres_0_2_0_types.PgValueBit:
			payload := element.Bit()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(31))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32((payload).F0)
			data22 := unsafe.Pointer(unsafe.SliceData((payload).F1))
			pinner.Pin(data22)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = uint32(uint32(len((payload).F1)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uintptr(uintptr(data22)))

		case wasmcloud_postgres_0_2_0_types.PgValueBitArray:
			payload := element.BitArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(32))
			slice24 := payload
			length26 := uint32(len(slice24))
			result25 := witRuntime.Allocate(pinner, uintptr(length26*(3*4)), 4)
			for index, element := range slice24 {
				base := unsafe.Add(result25, index*(3*4))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 0)) = int32((element).F0)
				data23 := unsafe.Pointer(unsafe.SliceData((element).F1))
				pinner.Pin(data23)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uint32(len((element).F1)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uintptr(uintptr(data23)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length26)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result25)))

		case wasmcloud_postgres_0_2_0_types.PgValueBitVarying:
			payload := element.BitVarying()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(33))

			switch (payload).F0.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).F0.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = int32(payload)

			default:
				panic("unreachable")
			}
			data27 := unsafe.Pointer(unsafe.SliceData((payload).F1))
			pinner.Pin(data27)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 1*4))) = uint32(uint32(len((payload).F1)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 16)) = uint32(uintptr(uintptr(data27)))

		case wasmcloud_postgres_0_2_0_types.PgValueVarbit:
			payload := element.Varbit()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(34))

			switch (payload).F0.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).F0.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = int32(payload)

			default:
				panic("unreachable")
			}
			data28 := unsafe.Pointer(unsafe.SliceData((payload).F1))
			pinner.Pin(data28)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 1*4))) = uint32(uint32(len((payload).F1)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 16)) = uint32(uintptr(uintptr(data28)))

		case wasmcloud_postgres_0_2_0_types.PgValueVarbitArray:
			payload := element.VarbitArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(35))
			slice30 := payload
			length32 := uint32(len(slice30))
			result31 := witRuntime.Allocate(pinner, uintptr(length32*(8+2*4)), 4)
			for index, element := range slice30 {
				base := unsafe.Add(result31, index*(8+2*4))

				switch (element).F0.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (element).F0.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 4)) = int32(payload)

				default:
					panic("unreachable")
				}
				data29 := unsafe.Pointer(unsafe.SliceData((element).F1))
				pinner.Pin(data29)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len((element).F1)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data29)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length32)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result31)))

		case wasmcloud_postgres_0_2_0_types.PgValueBytea:
			payload := element.Bytea()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(36))
			data33 := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data33)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data33)))

		case wasmcloud_postgres_0_2_0_types.PgValueByteaArray:
			payload := element.ByteaArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(37))
			slice35 := payload
			length37 := uint32(len(slice35))
			result36 := witRuntime.Allocate(pinner, uintptr(length37*(2*4)), 4)
			for index, element := range slice35 {
				base := unsafe.Add(result36, index*(2*4))
				data34 := unsafe.Pointer(unsafe.SliceData(element))
				pinner.Pin(data34)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(data34)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length37)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result36)))

		case wasmcloud_postgres_0_2_0_types.PgValueChar:
			payload := element.Char()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(38))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32((payload).F0)
			data38 := unsafe.Pointer(unsafe.SliceData((payload).F1))
			pinner.Pin(data38)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = uint32(uint32(len((payload).F1)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uintptr(uintptr(data38)))

		case wasmcloud_postgres_0_2_0_types.PgValueCharArray:
			payload := element.CharArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(39))
			slice40 := payload
			length42 := uint32(len(slice40))
			result41 := witRuntime.Allocate(pinner, uintptr(length42*(3*4)), 4)
			for index, element := range slice40 {
				base := unsafe.Add(result41, index*(3*4))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 0)) = int32((element).F0)
				data39 := unsafe.Pointer(unsafe.SliceData((element).F1))
				pinner.Pin(data39)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uint32(len((element).F1)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uintptr(uintptr(data39)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length42)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result41)))

		case wasmcloud_postgres_0_2_0_types.PgValueVarchar:
			payload := element.Varchar()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(40))

			switch (payload).F0.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (payload).F0.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = int32(payload)

			default:
				panic("unreachable")
			}
			data43 := unsafe.Pointer(unsafe.SliceData((payload).F1))
			pinner.Pin(data43)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 1*4))) = uint32(uint32(len((payload).F1)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 16)) = uint32(uintptr(uintptr(data43)))

		case wasmcloud_postgres_0_2_0_types.PgValueVarcharArray:
			payload := element.VarcharArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(41))
			slice45 := payload
			length47 := uint32(len(slice45))
			result46 := witRuntime.Allocate(pinner, uintptr(length47*(8+2*4)), 4)
			for index, element := range slice45 {
				base := unsafe.Add(result46, index*(8+2*4))

				switch (element).F0.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (element).F0.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 4)) = int32(payload)

				default:
					panic("unreachable")
				}
				data44 := unsafe.Pointer(unsafe.SliceData((element).F1))
				pinner.Pin(data44)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len((element).F1)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data44)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length47)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result46)))

		case wasmcloud_postgres_0_2_0_types.PgValueCidr:
			payload := element.Cidr()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(42))
			utf848 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf848)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf848)))

		case wasmcloud_postgres_0_2_0_types.PgValueCidrArray:
			payload := element.CidrArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(43))
			slice50 := payload
			length52 := uint32(len(slice50))
			result51 := witRuntime.Allocate(pinner, uintptr(length52*(2*4)), 4)
			for index, element := range slice50 {
				base := unsafe.Add(result51, index*(2*4))
				utf849 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf849)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf849)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length52)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result51)))

		case wasmcloud_postgres_0_2_0_types.PgValueInet:
			payload := element.Inet()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(44))
			utf853 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf853)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf853)))

		case wasmcloud_postgres_0_2_0_types.PgValueInetArray:
			payload := element.InetArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(45))
			slice55 := payload
			length57 := uint32(len(slice55))
			result56 := witRuntime.Allocate(pinner, uintptr(length57*(2*4)), 4)
			for index, element := range slice55 {
				base := unsafe.Add(result56, index*(2*4))
				utf854 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf854)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf854)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length57)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result56)))

		case wasmcloud_postgres_0_2_0_types.PgValueMacaddr:
			payload := element.Macaddr()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(46))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(((payload).Bytes).F0))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 9)) = int8(int32(((payload).Bytes).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32(((payload).Bytes).F2))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 11)) = int8(int32(((payload).Bytes).F3))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 12)) = int8(int32(((payload).Bytes).F4))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 13)) = int8(int32(((payload).Bytes).F5))

		case wasmcloud_postgres_0_2_0_types.PgValueMacaddrArray:
			payload := element.MacaddrArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(47))
			slice58 := payload
			length60 := uint32(len(slice58))
			result59 := witRuntime.Allocate(pinner, uintptr(length60*6), 1)
			for index, element := range slice58 {
				base := unsafe.Add(result59, index*6)
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(((element).Bytes).F0))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 1)) = int8(int32(((element).Bytes).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 2)) = int8(int32(((element).Bytes).F2))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 3)) = int8(int32(((element).Bytes).F3))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 4)) = int8(int32(((element).Bytes).F4))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 5)) = int8(int32(((element).Bytes).F5))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length60)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result59)))

		case wasmcloud_postgres_0_2_0_types.PgValueMacaddr8:
			payload := element.Macaddr8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(48))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(((payload).Bytes).F0))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 9)) = int8(int32(((payload).Bytes).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32(((payload).Bytes).F2))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 11)) = int8(int32(((payload).Bytes).F3))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 12)) = int8(int32(((payload).Bytes).F4))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 13)) = int8(int32(((payload).Bytes).F5))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 14)) = int8(int32(((payload).Bytes).F6))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 15)) = int8(int32(((payload).Bytes).F7))

		case wasmcloud_postgres_0_2_0_types.PgValueMacaddr8Array:
			payload := element.Macaddr8Array()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(49))
			slice61 := payload
			length63 := uint32(len(slice61))
			result62 := witRuntime.Allocate(pinner, uintptr(length63*8), 1)
			for index, element := range slice61 {
				base := unsafe.Add(result62, index*8)
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(((element).Bytes).F0))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 1)) = int8(int32(((element).Bytes).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 2)) = int8(int32(((element).Bytes).F2))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 3)) = int8(int32(((element).Bytes).F3))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 4)) = int8(int32(((element).Bytes).F4))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 5)) = int8(int32(((element).Bytes).F5))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 6)) = int8(int32(((element).Bytes).F6))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 7)) = int8(int32(((element).Bytes).F7))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length63)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result62)))

		case wasmcloud_postgres_0_2_0_types.PgValueBox:
			payload := element.Box()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(50))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64((((payload).F0).F0).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 16)) = int16(int32((((payload).F0).F0).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 18)) = int8(int32((((payload).F0).F0).F2))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 24)) = int64((((payload).F0).F1).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 32)) = int16(int32((((payload).F0).F1).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 34)) = int8(int32((((payload).F0).F1).F2))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 40)) = int64((((payload).F1).F0).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 48)) = int16(int32((((payload).F1).F0).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 50)) = int8(int32((((payload).F1).F0).F2))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64((((payload).F1).F1).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 64)) = int16(int32((((payload).F1).F1).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 66)) = int8(int32((((payload).F1).F1).F2))

		case wasmcloud_postgres_0_2_0_types.PgValueBoxArray:
			payload := element.BoxArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(51))
			slice64 := payload
			length66 := uint32(len(slice64))
			result65 := witRuntime.Allocate(pinner, uintptr(length66*64), 8)
			for index, element := range slice64 {
				base := unsafe.Add(result65, index*64)
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)) = int64((((element).F0).F0).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32((((element).F0).F0).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32((((element).F0).F0).F2))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 16)) = int64((((element).F0).F1).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 24)) = int16(int32((((element).F0).F1).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 26)) = int8(int32((((element).F0).F1).F2))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64((((element).F1).F0).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 40)) = int16(int32((((element).F1).F0).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 42)) = int8(int32((((element).F1).F0).F2))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 48)) = int64((((element).F1).F1).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 56)) = int16(int32((((element).F1).F1).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 58)) = int8(int32((((element).F1).F1).F2))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length66)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result65)))

		case wasmcloud_postgres_0_2_0_types.PgValueCircle:
			payload := element.Circle()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(52))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64((((payload).F0).F0).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 16)) = int16(int32((((payload).F0).F0).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 18)) = int8(int32((((payload).F0).F0).F2))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 24)) = int64((((payload).F0).F1).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 32)) = int16(int32((((payload).F0).F1).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 34)) = int8(int32((((payload).F0).F1).F2))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 40)) = int64(((payload).F1).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 48)) = int16(int32(((payload).F1).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 50)) = int8(int32(((payload).F1).F2))

		case wasmcloud_postgres_0_2_0_types.PgValueCircleArray:
			payload := element.CircleArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(53))
			slice67 := payload
			length69 := uint32(len(slice67))
			result68 := witRuntime.Allocate(pinner, uintptr(length69*48), 8)
			for index, element := range slice67 {
				base := unsafe.Add(result68, index*48)
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)) = int64((((element).F0).F0).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32((((element).F0).F0).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32((((element).F0).F0).F2))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 16)) = int64((((element).F0).F1).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 24)) = int16(int32((((element).F0).F1).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 26)) = int8(int32((((element).F0).F1).F2))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64(((element).F1).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 40)) = int16(int32(((element).F1).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 42)) = int8(int32(((element).F1).F2))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length69)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result68)))

		case wasmcloud_postgres_0_2_0_types.PgValueLine:
			payload := element.Line()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(54))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64((((payload).F0).F0).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 16)) = int16(int32((((payload).F0).F0).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 18)) = int8(int32((((payload).F0).F0).F2))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 24)) = int64((((payload).F0).F1).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 32)) = int16(int32((((payload).F0).F1).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 34)) = int8(int32((((payload).F0).F1).F2))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 40)) = int64((((payload).F1).F0).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 48)) = int16(int32((((payload).F1).F0).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 50)) = int8(int32((((payload).F1).F0).F2))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64((((payload).F1).F1).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 64)) = int16(int32((((payload).F1).F1).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 66)) = int8(int32((((payload).F1).F1).F2))

		case wasmcloud_postgres_0_2_0_types.PgValueLineArray:
			payload := element.LineArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(55))
			slice70 := payload
			length72 := uint32(len(slice70))
			result71 := witRuntime.Allocate(pinner, uintptr(length72*64), 8)
			for index, element := range slice70 {
				base := unsafe.Add(result71, index*64)
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)) = int64((((element).F0).F0).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32((((element).F0).F0).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32((((element).F0).F0).F2))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 16)) = int64((((element).F0).F1).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 24)) = int16(int32((((element).F0).F1).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 26)) = int8(int32((((element).F0).F1).F2))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64((((element).F1).F0).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 40)) = int16(int32((((element).F1).F0).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 42)) = int8(int32((((element).F1).F0).F2))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 48)) = int64((((element).F1).F1).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 56)) = int16(int32((((element).F1).F1).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 58)) = int8(int32((((element).F1).F1).F2))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length72)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result71)))

		case wasmcloud_postgres_0_2_0_types.PgValueLseg:
			payload := element.Lseg()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(56))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64((((payload).F0).F0).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 16)) = int16(int32((((payload).F0).F0).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 18)) = int8(int32((((payload).F0).F0).F2))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 24)) = int64((((payload).F0).F1).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 32)) = int16(int32((((payload).F0).F1).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 34)) = int8(int32((((payload).F0).F1).F2))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 40)) = int64((((payload).F1).F0).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 48)) = int16(int32((((payload).F1).F0).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 50)) = int8(int32((((payload).F1).F0).F2))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 56)) = int64((((payload).F1).F1).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 64)) = int16(int32((((payload).F1).F1).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 66)) = int8(int32((((payload).F1).F1).F2))

		case wasmcloud_postgres_0_2_0_types.PgValueLsegArray:
			payload := element.LsegArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(57))
			slice73 := payload
			length75 := uint32(len(slice73))
			result74 := witRuntime.Allocate(pinner, uintptr(length75*64), 8)
			for index, element := range slice73 {
				base := unsafe.Add(result74, index*64)
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)) = int64((((element).F0).F0).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32((((element).F0).F0).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32((((element).F0).F0).F2))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 16)) = int64((((element).F0).F1).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 24)) = int16(int32((((element).F0).F1).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 26)) = int8(int32((((element).F0).F1).F2))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)) = int64((((element).F1).F0).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 40)) = int16(int32((((element).F1).F0).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 42)) = int8(int32((((element).F1).F0).F2))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 48)) = int64((((element).F1).F1).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 56)) = int16(int32((((element).F1).F1).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 58)) = int8(int32((((element).F1).F1).F2))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length75)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result74)))

		case wasmcloud_postgres_0_2_0_types.PgValuePath:
			payload := element.Path()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(58))
			slice76 := payload
			length78 := uint32(len(slice76))
			result77 := witRuntime.Allocate(pinner, uintptr(length78*32), 8)
			for index, element := range slice76 {
				base := unsafe.Add(result77, index*32)
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)) = int64(((element).F0).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(((element).F0).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32(((element).F0).F2))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 16)) = int64(((element).F1).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 24)) = int16(int32(((element).F1).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 26)) = int8(int32(((element).F1).F2))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length78)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result77)))

		case wasmcloud_postgres_0_2_0_types.PgValuePathArray:
			payload := element.PathArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(59))
			slice82 := payload
			length84 := uint32(len(slice82))
			result83 := witRuntime.Allocate(pinner, uintptr(length84*(2*4)), 4)
			for index, element := range slice82 {
				base := unsafe.Add(result83, index*(2*4))
				slice79 := element
				length81 := uint32(len(slice79))
				result80 := witRuntime.Allocate(pinner, uintptr(length81*32), 8)
				for index, element := range slice79 {
					base := unsafe.Add(result80, index*32)
					*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)) = int64(((element).F0).F0)
					*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(((element).F0).F1))
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32(((element).F0).F2))
					*(*int64)(unsafe.Add(unsafe.Pointer(base), 16)) = int64(((element).F1).F0)
					*(*int16)(unsafe.Add(unsafe.Pointer(base), 24)) = int16(int32(((element).F1).F1))
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 26)) = int8(int32(((element).F1).F2))

				}

				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(length81)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(result80)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length84)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result83)))

		case wasmcloud_postgres_0_2_0_types.PgValuePoint:
			payload := element.Point()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(60))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64(((payload).F0).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 16)) = int16(int32(((payload).F0).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 18)) = int8(int32(((payload).F0).F2))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 24)) = int64(((payload).F1).F0)
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 32)) = int16(int32(((payload).F1).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 34)) = int8(int32(((payload).F1).F2))

		case wasmcloud_postgres_0_2_0_types.PgValuePointArray:
			payload := element.PointArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(61))
			slice85 := payload
			length87 := uint32(len(slice85))
			result86 := witRuntime.Allocate(pinner, uintptr(length87*32), 8)
			for index, element := range slice85 {
				base := unsafe.Add(result86, index*32)
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)) = int64(((element).F0).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(((element).F0).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32(((element).F0).F2))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 16)) = int64(((element).F1).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 24)) = int16(int32(((element).F1).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 26)) = int8(int32(((element).F1).F2))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length87)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result86)))

		case wasmcloud_postgres_0_2_0_types.PgValuePolygon:
			payload := element.Polygon()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(62))
			slice88 := payload
			length90 := uint32(len(slice88))
			result89 := witRuntime.Allocate(pinner, uintptr(length90*32), 8)
			for index, element := range slice88 {
				base := unsafe.Add(result89, index*32)
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)) = int64(((element).F0).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(((element).F0).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32(((element).F0).F2))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), 16)) = int64(((element).F1).F0)
				*(*int16)(unsafe.Add(unsafe.Pointer(base), 24)) = int16(int32(((element).F1).F1))
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 26)) = int8(int32(((element).F1).F2))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length90)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result89)))

		case wasmcloud_postgres_0_2_0_types.PgValuePolygonArray:
			payload := element.PolygonArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(63))
			slice94 := payload
			length96 := uint32(len(slice94))
			result95 := witRuntime.Allocate(pinner, uintptr(length96*(2*4)), 4)
			for index, element := range slice94 {
				base := unsafe.Add(result95, index*(2*4))
				slice91 := element
				length93 := uint32(len(slice91))
				result92 := witRuntime.Allocate(pinner, uintptr(length93*32), 8)
				for index, element := range slice91 {
					base := unsafe.Add(result92, index*32)
					*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)) = int64(((element).F0).F0)
					*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(((element).F0).F1))
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32(((element).F0).F2))
					*(*int64)(unsafe.Add(unsafe.Pointer(base), 16)) = int64(((element).F1).F0)
					*(*int16)(unsafe.Add(unsafe.Pointer(base), 24)) = int16(int32(((element).F1).F1))
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 26)) = int8(int32(((element).F1).F2))

				}

				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(length93)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(result92)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length96)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result95)))

		case wasmcloud_postgres_0_2_0_types.PgValueDate:
			payload := element.Date()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(64))

			switch payload.Tag() {
			case wasmcloud_postgres_0_2_0_types.DatePositiveInfinity:

				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case wasmcloud_postgres_0_2_0_types.DateNegativeInfinity:

				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))

			case wasmcloud_postgres_0_2_0_types.DateYmd:
				payload := payload.Ymd()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(2))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = (payload).F0
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 16)) = int32((payload).F1)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 20)) = int32((payload).F2)

			default:
				panic("unreachable")
			}

		case wasmcloud_postgres_0_2_0_types.PgValueDateArray:
			payload := element.DateArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(65))
			slice97 := payload
			length99 := uint32(len(slice97))
			result98 := witRuntime.Allocate(pinner, uintptr(length99*16), 4)
			for index, element := range slice97 {
				base := unsafe.Add(result98, index*16)

				switch element.Tag() {
				case wasmcloud_postgres_0_2_0_types.DatePositiveInfinity:

					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))

				case wasmcloud_postgres_0_2_0_types.DateNegativeInfinity:

					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))

				case wasmcloud_postgres_0_2_0_types.DateYmd:
					payload := element.Ymd()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 4)) = (payload).F0
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32((payload).F1)
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = int32((payload).F2)

				default:
					panic("unreachable")
				}

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length99)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result98)))

		case wasmcloud_postgres_0_2_0_types.PgValueInterval:
			payload := element.Interval()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(66))

			switch (payload).Start.Tag() {
			case wasmcloud_postgres_0_2_0_types.DatePositiveInfinity:

				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case wasmcloud_postgres_0_2_0_types.DateNegativeInfinity:

				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))

			case wasmcloud_postgres_0_2_0_types.DateYmd:
				payload := (payload).Start.Ymd()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(2))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = (payload).F0
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 16)) = int32((payload).F1)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 20)) = int32((payload).F2)

			default:
				panic("unreachable")
			}
			var result100 int32
			if (payload).StartInclusive {
				result100 = 1
			} else {
				result100 = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 24)) = int8(result100)

			switch (payload).End.Tag() {
			case wasmcloud_postgres_0_2_0_types.DatePositiveInfinity:

				*(*int8)(unsafe.Add(unsafe.Pointer(base), 28)) = int8(int32(0))

			case wasmcloud_postgres_0_2_0_types.DateNegativeInfinity:

				*(*int8)(unsafe.Add(unsafe.Pointer(base), 28)) = int8(int32(1))

			case wasmcloud_postgres_0_2_0_types.DateYmd:
				payload := (payload).End.Ymd()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 28)) = int8(int32(2))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 32)) = (payload).F0
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 36)) = int32((payload).F1)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 40)) = int32((payload).F2)

			default:
				panic("unreachable")
			}
			var result101 int32
			if (payload).EndInclusive {
				result101 = 1
			} else {
				result101 = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 44)) = int8(result101)

		case wasmcloud_postgres_0_2_0_types.PgValueIntervalArray:
			payload := element.IntervalArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(67))
			slice104 := payload
			length106 := uint32(len(slice104))
			result105 := witRuntime.Allocate(pinner, uintptr(length106*40), 4)
			for index, element := range slice104 {
				base := unsafe.Add(result105, index*40)

				switch (element).Start.Tag() {
				case wasmcloud_postgres_0_2_0_types.DatePositiveInfinity:

					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))

				case wasmcloud_postgres_0_2_0_types.DateNegativeInfinity:

					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))

				case wasmcloud_postgres_0_2_0_types.DateYmd:
					payload := (element).Start.Ymd()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 4)) = (payload).F0
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32((payload).F1)
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = int32((payload).F2)

				default:
					panic("unreachable")
				}
				var result102 int32
				if (element).StartInclusive {
					result102 = 1
				} else {
					result102 = 0
				}
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(result102)

				switch (element).End.Tag() {
				case wasmcloud_postgres_0_2_0_types.DatePositiveInfinity:

					*(*int8)(unsafe.Add(unsafe.Pointer(base), 20)) = int8(int32(0))

				case wasmcloud_postgres_0_2_0_types.DateNegativeInfinity:

					*(*int8)(unsafe.Add(unsafe.Pointer(base), 20)) = int8(int32(1))

				case wasmcloud_postgres_0_2_0_types.DateYmd:
					payload := (element).End.Ymd()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 20)) = int8(int32(2))
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 24)) = (payload).F0
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 28)) = int32((payload).F1)
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 32)) = int32((payload).F2)

				default:
					panic("unreachable")
				}
				var result103 int32
				if (element).EndInclusive {
					result103 = 1
				} else {
					result103 = 0
				}
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 36)) = int8(result103)

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length106)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result105)))

		case wasmcloud_postgres_0_2_0_types.PgValueTime:
			payload := element.Time()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(68))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32((payload).Hour)
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = int32((payload).Min)
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 16)) = int32((payload).Sec)
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 20)) = int32((payload).Micro)

		case wasmcloud_postgres_0_2_0_types.PgValueTimeArray:
			payload := element.TimeArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(69))
			slice107 := payload
			length109 := uint32(len(slice107))
			result108 := witRuntime.Allocate(pinner, uintptr(length109*16), 4)
			for index, element := range slice107 {
				base := unsafe.Add(result108, index*16)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 0)) = int32((element).Hour)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 4)) = int32((element).Min)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32((element).Sec)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = int32((element).Micro)

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length109)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result108)))

		case wasmcloud_postgres_0_2_0_types.PgValueTimeTz:
			payload := element.TimeTz()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(70))
			utf8110 := unsafe.Pointer(unsafe.StringData((payload).Timesonze))
			pinner.Pin(utf8110)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len((payload).Timesonze)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf8110)))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = int32(((payload).Time).Hour)
			*(*int32)(unsafe.Add(unsafe.Pointer(base), (12 + 2*4))) = int32(((payload).Time).Min)
			*(*int32)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4))) = int32(((payload).Time).Sec)
			*(*int32)(unsafe.Add(unsafe.Pointer(base), (20 + 2*4))) = int32(((payload).Time).Micro)

		case wasmcloud_postgres_0_2_0_types.PgValueTimeTzArray:
			payload := element.TimeTzArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(71))
			slice112 := payload
			length114 := uint32(len(slice112))
			result113 := witRuntime.Allocate(pinner, uintptr(length114*(16+2*4)), 4)
			for index, element := range slice112 {
				base := unsafe.Add(result113, index*(16+2*4))
				utf8111 := unsafe.Pointer(unsafe.StringData((element).Timesonze))
				pinner.Pin(utf8111)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).Timesonze)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8111)))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = int32(((element).Time).Hour)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 2*4))) = int32(((element).Time).Min)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = int32(((element).Time).Sec)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (12 + 2*4))) = int32(((element).Time).Micro)

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length114)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result113)))

		case wasmcloud_postgres_0_2_0_types.PgValueTimestamp:
			payload := element.Timestamp()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(72))

			switch (payload).Date.Tag() {
			case wasmcloud_postgres_0_2_0_types.DatePositiveInfinity:

				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case wasmcloud_postgres_0_2_0_types.DateNegativeInfinity:

				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))

			case wasmcloud_postgres_0_2_0_types.DateYmd:
				payload := (payload).Date.Ymd()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(2))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = (payload).F0
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 16)) = int32((payload).F1)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 20)) = int32((payload).F2)

			default:
				panic("unreachable")
			}
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 24)) = int32(((payload).Time).Hour)
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 28)) = int32(((payload).Time).Min)
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 32)) = int32(((payload).Time).Sec)
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 36)) = int32(((payload).Time).Micro)

		case wasmcloud_postgres_0_2_0_types.PgValueTimestampArray:
			payload := element.TimestampArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(73))
			slice115 := payload
			length117 := uint32(len(slice115))
			result116 := witRuntime.Allocate(pinner, uintptr(length117*32), 4)
			for index, element := range slice115 {
				base := unsafe.Add(result116, index*32)

				switch (element).Date.Tag() {
				case wasmcloud_postgres_0_2_0_types.DatePositiveInfinity:

					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))

				case wasmcloud_postgres_0_2_0_types.DateNegativeInfinity:

					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))

				case wasmcloud_postgres_0_2_0_types.DateYmd:
					payload := (element).Date.Ymd()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 4)) = (payload).F0
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32((payload).F1)
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = int32((payload).F2)

				default:
					panic("unreachable")
				}
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 16)) = int32(((element).Time).Hour)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 20)) = int32(((element).Time).Min)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 24)) = int32(((element).Time).Sec)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 28)) = int32(((element).Time).Micro)

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length117)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result116)))

		case wasmcloud_postgres_0_2_0_types.PgValueTimestampTz:
			payload := element.TimestampTz()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(74))

			switch ((payload).Timestamp).Date.Tag() {
			case wasmcloud_postgres_0_2_0_types.DatePositiveInfinity:

				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))

			case wasmcloud_postgres_0_2_0_types.DateNegativeInfinity:

				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))

			case wasmcloud_postgres_0_2_0_types.DateYmd:
				payload := ((payload).Timestamp).Date.Ymd()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(2))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = (payload).F0
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 16)) = int32((payload).F1)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 20)) = int32((payload).F2)

			default:
				panic("unreachable")
			}
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 24)) = int32((((payload).Timestamp).Time).Hour)
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 28)) = int32((((payload).Timestamp).Time).Min)
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 32)) = int32((((payload).Timestamp).Time).Sec)
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 36)) = int32((((payload).Timestamp).Time).Micro)

			switch (payload).Offset.Tag() {
			case wasmcloud_postgres_0_2_0_types.OffsetEasternHemisphereSecs:
				payload := (payload).Offset.EasternHemisphereSecs()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(0))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 44)) = payload

			case wasmcloud_postgres_0_2_0_types.OffsetWesternHemisphereSecs:
				payload := (payload).Offset.WesternHemisphereSecs()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 40)) = int8(int32(1))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 44)) = payload

			default:
				panic("unreachable")
			}

		case wasmcloud_postgres_0_2_0_types.PgValueTimestampTzArray:
			payload := element.TimestampTzArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(75))
			slice118 := payload
			length120 := uint32(len(slice118))
			result119 := witRuntime.Allocate(pinner, uintptr(length120*40), 4)
			for index, element := range slice118 {
				base := unsafe.Add(result119, index*40)

				switch ((element).Timestamp).Date.Tag() {
				case wasmcloud_postgres_0_2_0_types.DatePositiveInfinity:

					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))

				case wasmcloud_postgres_0_2_0_types.DateNegativeInfinity:

					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))

				case wasmcloud_postgres_0_2_0_types.DateYmd:
					payload := ((element).Timestamp).Date.Ymd()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 4)) = (payload).F0
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32((payload).F1)
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = int32((payload).F2)

				default:
					panic("unreachable")
				}
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 16)) = int32((((element).Timestamp).Time).Hour)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 20)) = int32((((element).Timestamp).Time).Min)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 24)) = int32((((element).Timestamp).Time).Sec)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), 28)) = int32((((element).Timestamp).Time).Micro)

				switch (element).Offset.Tag() {
				case wasmcloud_postgres_0_2_0_types.OffsetEasternHemisphereSecs:
					payload := (element).Offset.EasternHemisphereSecs()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 32)) = int8(int32(0))
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 36)) = payload

				case wasmcloud_postgres_0_2_0_types.OffsetWesternHemisphereSecs:
					payload := (element).Offset.WesternHemisphereSecs()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 32)) = int8(int32(1))
					*(*int32)(unsafe.Add(unsafe.Pointer(base), 36)) = payload

				default:
					panic("unreachable")
				}

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length120)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result119)))

		case wasmcloud_postgres_0_2_0_types.PgValueJson:
			payload := element.Json()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(76))
			utf8121 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8121)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf8121)))

		case wasmcloud_postgres_0_2_0_types.PgValueJsonArray:
			payload := element.JsonArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(77))
			slice123 := payload
			length125 := uint32(len(slice123))
			result124 := witRuntime.Allocate(pinner, uintptr(length125*(2*4)), 4)
			for index, element := range slice123 {
				base := unsafe.Add(result124, index*(2*4))
				utf8122 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf8122)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8122)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length125)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result124)))

		case wasmcloud_postgres_0_2_0_types.PgValueJsonb:
			payload := element.Jsonb()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(78))
			utf8126 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8126)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf8126)))

		case wasmcloud_postgres_0_2_0_types.PgValueJsonbArray:
			payload := element.JsonbArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(79))
			slice128 := payload
			length130 := uint32(len(slice128))
			result129 := witRuntime.Allocate(pinner, uintptr(length130*(2*4)), 4)
			for index, element := range slice128 {
				base := unsafe.Add(result129, index*(2*4))
				utf8127 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf8127)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8127)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length130)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result129)))

		case wasmcloud_postgres_0_2_0_types.PgValueMoney:
			payload := element.Money()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(80))
			utf8131 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8131)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf8131)))

		case wasmcloud_postgres_0_2_0_types.PgValueMoneyArray:
			payload := element.MoneyArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(81))
			slice133 := payload
			length135 := uint32(len(slice133))
			result134 := witRuntime.Allocate(pinner, uintptr(length135*(2*4)), 4)
			for index, element := range slice133 {
				base := unsafe.Add(result134, index*(2*4))
				utf8132 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf8132)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8132)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length135)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result134)))

		case wasmcloud_postgres_0_2_0_types.PgValuePgLsn:
			payload := element.PgLsn()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(82))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64(payload)

		case wasmcloud_postgres_0_2_0_types.PgValuePgLsnArray:
			payload := element.PgLsnArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(83))
			data136 := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data136)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data136)))

		case wasmcloud_postgres_0_2_0_types.PgValuePgSnapshot:
			payload := element.PgSnapshot()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(84))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = (payload).F0
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 16)) = (payload).F1
			data137 := unsafe.Pointer(unsafe.SliceData((payload).F2))
			pinner.Pin(data137)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 1*4))) = uint32(uint32(len((payload).F2)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 24)) = uint32(uintptr(uintptr(data137)))

		case wasmcloud_postgres_0_2_0_types.PgValueTxidSnapshot:
			payload := element.TxidSnapshot()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(85))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case wasmcloud_postgres_0_2_0_types.PgValueName:
			payload := element.Name()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(86))
			utf8138 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8138)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf8138)))

		case wasmcloud_postgres_0_2_0_types.PgValueNameArray:
			payload := element.NameArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(87))
			slice140 := payload
			length142 := uint32(len(slice140))
			result141 := witRuntime.Allocate(pinner, uintptr(length142*(2*4)), 4)
			for index, element := range slice140 {
				base := unsafe.Add(result141, index*(2*4))
				utf8139 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf8139)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8139)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length142)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result141)))

		case wasmcloud_postgres_0_2_0_types.PgValueText:
			payload := element.Text()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(88))
			utf8143 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8143)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf8143)))

		case wasmcloud_postgres_0_2_0_types.PgValueTextArray:
			payload := element.TextArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(89))
			slice145 := payload
			length147 := uint32(len(slice145))
			result146 := witRuntime.Allocate(pinner, uintptr(length147*(2*4)), 4)
			for index, element := range slice145 {
				base := unsafe.Add(result146, index*(2*4))
				utf8144 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf8144)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8144)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length147)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result146)))

		case wasmcloud_postgres_0_2_0_types.PgValueXml:
			payload := element.Xml()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(90))
			utf8148 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8148)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf8148)))

		case wasmcloud_postgres_0_2_0_types.PgValueXmlArray:
			payload := element.XmlArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(91))
			slice150 := payload
			length152 := uint32(len(slice150))
			result151 := witRuntime.Allocate(pinner, uintptr(length152*(2*4)), 4)
			for index, element := range slice150 {
				base := unsafe.Add(result151, index*(2*4))
				utf8149 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf8149)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8149)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length152)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result151)))

		case wasmcloud_postgres_0_2_0_types.PgValueTsQuery:
			payload := element.TsQuery()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(92))
			utf8153 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8153)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf8153)))

		case wasmcloud_postgres_0_2_0_types.PgValueTsVector:
			payload := element.TsVector()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(93))
			slice155 := payload
			length157 := uint32(len(slice155))
			result156 := witRuntime.Allocate(pinner, uintptr(length157*(8+2*4)), 4)
			for index, element := range slice155 {
				base := unsafe.Add(result156, index*(8+2*4))

				switch (element).Position.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (element).Position.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
					*(*int16)(unsafe.Add(unsafe.Pointer(base), 2)) = int16(int32(payload))

				default:
					panic("unreachable")
				}

				switch (element).Weight.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 4)) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (element).Weight.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 4)) = int8(int32(1))
					*(*int8)(unsafe.Add(unsafe.Pointer(base), 5)) = int8(int32(payload))

				default:
					panic("unreachable")
				}
				utf8154 := unsafe.Pointer(unsafe.StringData((element).Data))
				pinner.Pin(utf8154)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len((element).Data)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf8154)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length157)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result156)))

		case wasmcloud_postgres_0_2_0_types.PgValueUuid:
			payload := element.Uuid()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(94))
			utf8158 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8158)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf8158)))

		case wasmcloud_postgres_0_2_0_types.PgValueUuidArray:
			payload := element.UuidArray()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(95))
			slice160 := payload
			length162 := uint32(len(slice160))
			result161 := witRuntime.Allocate(pinner, uintptr(length162*(2*4)), 4)
			for index, element := range slice160 {
				base := unsafe.Add(result161, index*(2*4))
				utf8159 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf8159)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8159)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length162)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result161)))

		case wasmcloud_postgres_0_2_0_types.PgValueHstore:
			payload := element.Hstore()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(96))
			slice165 := payload
			length167 := uint32(len(slice165))
			result166 := witRuntime.Allocate(pinner, uintptr(length167*(5*4)), 4)
			for index, element := range slice165 {
				base := unsafe.Add(result166, index*(5*4))
				utf8163 := unsafe.Pointer(unsafe.StringData((element).F0))
				pinner.Pin(utf8163)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).F0)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8163)))

				switch (element).F1.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (element).F1.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = int8(int32(1))
					utf8164 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf8164)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = uint32(uintptr(uintptr(utf8164)))

				default:
					panic("unreachable")
				}

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(length167)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(result166)))

		default:
			panic("unreachable")
		}

	}

	witAsync.SubtaskWait(uint32(wasm_import_exec(uintptr(utf8), uint32(len(stmtToken)), uintptr(result169), length170, returnArea)))
	var result182 witTypes.Result[uint64, wasmcloud_postgres_0_2_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result182 = witTypes.Ok[uint64, wasmcloud_postgres_0_2_0_types.Error](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
	case 1:
		var variant wasmcloud_postgres_0_2_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorConnectionFailed(value)

		case 1:
			value171 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorInvalidParams(value171)

		case 2:
			value172 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorInvalidQuery(value172)

		case 3:
			value173 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))
			value174 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 4*4))))
			value175 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 5*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 6*4))))
			var option witTypes.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 7*4)))) {
			case 0:

				option = witTypes.None[string]()
			case 1:
				value176 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 8*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 9*4))))

				option = witTypes.Some[string](value176)
			default:
				panic("unreachable")
			}
			result179 := make([]witTypes.Tuple2[string, string], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 11*4))))
			for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 11*4)))); index++ {
				base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 10*4))))), index*(4*4))
				value177 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
				value178 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

				result179 = append(result179, witTypes.Tuple2[string, string]{value177, value178})
			}

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorQueryFailed(wasmcloud_postgres_0_2_0_types.DbError{value173, value174, value175, option, result179})

		case 4:
			value180 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorValueConversionFailed(value180)

		case 5:

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorUnknownPreparedStatement()

		case 6:

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorAccessDenied()

		case 7:

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorTimeout()

		case 8:
			value181 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = wasmcloud_postgres_0_2_0_types.MakeErrorOther(value181)

		default:
			panic("unreachable")
		}

		result182 = witTypes.Err[uint64, wasmcloud_postgres_0_2_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result182

}
