// Generated by `wit-bindgen` 0.61.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.1.0
//     wasmcloud:keyvalue@0.2.0
//     wasmcloud:messaging@0.3.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0

package wasmcloud_keyvalue_0_2_0_batch

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"go.wasmcloud.dev/component/imports/wasmcloud_keyvalue_0_2_0_types"
	"runtime"
	"unsafe"
)

type Bucket = wasmcloud_keyvalue_0_2_0_types.Bucket
type Error = wasmcloud_keyvalue_0_2_0_types.Error

//go:wasmimport wasmcloud:keyvalue/batch@0.2.0 [async-lower]get-many
func wasm_import_get_many(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr) int32

func GetMany(bucket *wasmcloud_keyvalue_0_2_0_types.Bucket, keys []string) witTypes.Result[[]witTypes.Option[witTypes.Tuple2[string, []uint8]], wasmcloud_keyvalue_0_2_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	slice := keys
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(2*4))
		utf8 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))

	}

	witAsync.SubtaskWait(uint32(wasm_import_get_many((bucket).Handle(), uintptr(result), length, returnArea)))
	var result3 witTypes.Result[[]witTypes.Option[witTypes.Tuple2[string, []uint8]], wasmcloud_keyvalue_0_2_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result1 := make([]witTypes.Option[witTypes.Tuple2[string, []uint8]], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(5*4))
			var option witTypes.Option[witTypes.Tuple2[string, []uint8]]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
			case 0:

				option = witTypes.None[witTypes.Tuple2[string, []uint8]]()
			case 1:
				value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))))
				value0 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))))

				option = witTypes.Some[witTypes.Tuple2[string, []uint8]](witTypes.Tuple2[string, []uint8]{F0: value, F1: value0})
			default:
				panic("unreachable")
			}

			result1 = append(result1, option)
		}

		result3 = witTypes.Ok[[]witTypes.Option[witTypes.Tuple2[string, []uint8]], wasmcloud_keyvalue_0_2_0_types.Error](result1)
	case 1:
		var variant wasmcloud_keyvalue_0_2_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorNoSuchStore()

		case 1:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorAccessDenied()

		case 2:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorInvalidArgument()

		case 3:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorPreconditionFailed()

		case 4:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorQuotaExceeded()

		case 7:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorOther(value2)

		default:
			panic("unreachable")
		}

		result3 = witTypes.Err[[]witTypes.Option[witTypes.Tuple2[string, []uint8]], wasmcloud_keyvalue_0_2_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result3

}

//go:wasmimport wasmcloud:keyvalue/batch@0.2.0 [async-lower]set-many
func wasm_import_set_many(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr) int32

func SetMany(bucket *wasmcloud_keyvalue_0_2_0_types.Bucket, keyValues []witTypes.Tuple2[string, []uint8]) witTypes.Result[witTypes.Unit, wasmcloud_keyvalue_0_2_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	slice := keyValues
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(4*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(4*4))
		utf8 := unsafe.Pointer(unsafe.StringData((element).F0))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).F0)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))
		data := unsafe.Pointer(unsafe.SliceData((element).F1))
		pinner.Pin(data)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = uint32(uint32(len((element).F1)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uintptr(uintptr(data)))

	}

	witAsync.SubtaskWait(uint32(wasm_import_set_many((bucket).Handle(), uintptr(result), length, returnArea)))
	var result0 witTypes.Result[witTypes.Unit, wasmcloud_keyvalue_0_2_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result0 = witTypes.Ok[witTypes.Unit, wasmcloud_keyvalue_0_2_0_types.Error](witTypes.Unit{})
	case 1:
		var variant wasmcloud_keyvalue_0_2_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorNoSuchStore()

		case 1:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorAccessDenied()

		case 2:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorInvalidArgument()

		case 3:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorPreconditionFailed()

		case 4:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result0 = witTypes.Err[witTypes.Unit, wasmcloud_keyvalue_0_2_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result0

}

//go:wasmimport wasmcloud:keyvalue/batch@0.2.0 [async-lower]delete-many
func wasm_import_delete_many(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr) int32

func DeleteMany(bucket *wasmcloud_keyvalue_0_2_0_types.Bucket, keys []string) witTypes.Result[witTypes.Unit, wasmcloud_keyvalue_0_2_0_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	slice := keys
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(2*4))
		utf8 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))

	}

	witAsync.SubtaskWait(uint32(wasm_import_delete_many((bucket).Handle(), uintptr(result), length, returnArea)))
	var result0 witTypes.Result[witTypes.Unit, wasmcloud_keyvalue_0_2_0_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result0 = witTypes.Ok[witTypes.Unit, wasmcloud_keyvalue_0_2_0_types.Error](witTypes.Unit{})
	case 1:
		var variant wasmcloud_keyvalue_0_2_0_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorNoSuchStore()

		case 1:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorAccessDenied()

		case 2:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorInvalidArgument()

		case 3:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorPreconditionFailed()

		case 4:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorTimeout()

		case 5:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorStoreUnavailable()

		case 6:

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorQuotaExceeded()

		case 7:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasmcloud_keyvalue_0_2_0_types.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result0 = witTypes.Err[witTypes.Unit, wasmcloud_keyvalue_0_2_0_types.Error](variant)
	default:
		panic("unreachable")
	}

	return result0

}
