// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:cli@0.3.0
//     wasi:clocks@0.3.0
//     wasi:config@0.2.0-rc.1
//     wasi:filesystem@0.3.0
//     wasi:http@0.2.8
//     wasi:random@0.3.0
//     wasi:http@0.3.0
//     wasi:logging@0.1.0-draft
//     wasi:sockets@0.3.0
//     wasmcloud:component-go@0.2.0
//     componentize-go:union

package wasi_random_0_2_8_random

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"runtime"
	"unsafe"
)

//go:wasmimport wasi:random/random@0.2.8 get-random-bytes
func wasm_import_get_random_bytes(arg0 int64, arg1 uintptr)

func GetRandomBytes(len uint64) []uint8 {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_get_random_bytes(int64(len), returnArea)
	value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := value
	return result

}

//go:wasmimport wasi:random/random@0.2.8 get-random-u64
func wasm_import_get_random_u64() int64

func GetRandomU64() uint64 {

	result := wasm_import_get_random_u64()
	return uint64(result)

}
